### ISSUE TITLE
KucoinSocketClient it simply does not respond and does not generate any error

### ISSUE THREAD

**Issue by juandfranco** [JKorf/Kucoin.Net#1]
Hi, I've been trying to use your apis and I have not been able to get them to work with the latest version of CryptoExchange.Net, only the socket works correctly in Coinex and Binance, when you download the versions separately with your source in Bitfinex and KuCoin in conjunction with your last CryptoExchange.Net version you only get errors, thank you very much for your organized and clean work          

```
  var clientKucoin = new KucoinSocketClient();

            var subscriptionKucoin = clientKucoin.SubscribeToAllTickerUpdates(data =>
            {
                var test = data;
                Console.WriteLine("Received list update");
            });
```

**Comment by JKorf** [comment]
Hi, can you try again with the latest versions? I've added ConfigureAwait(false) on various places which could resolve the freezing you saw. Are you running from a winform or wpf application?  If you get errors, could you share them?

**Comment by juandfranco** [comment]
Thank you very much Jan, now it works correctly, I'm doing a windows form application, any inconvenience I'll be bothering you, very good your api, you saved me a lot of way
