### ISSUE TITLE
Size error in Futures PlaceOrderAsync

### ISSUE THREAD

**Issue by hyperms** [JKorf/Kucoin.Net#100]
Hi
The problem with the Kucoin API is that the size field cannot be sent as decimal in PlaceOrderAsync because this field is considered as integer in their API documentation.

![image](https://user-images.githubusercontent.com/72021670/146171943-9970c7dd-808b-4a88-8c26-603f78c3d204.png)

For example, you can't trade Bitcoin because it requires at least $ 50,000
Is there a solution to this problem?

**Comment by MAlikhanian** [comment]
> Hi
> 
> The problem with the Kucoin API is that the size field cannot be sent as decimal in PlaceOrderAsync because this field is considered as integer in their API documentation.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/72021670/146171943-9970c7dd-808b-4a88-8c26-603f78c3d204.png)
> 
> 
> 
> For example, you can't trade Bitcoin because it requires at least $ 50,000
> 
> Is there a solution to this problem?

I have this problem to🥺

**Comment by MAlikhanian** [comment]
> Hi
> 
> The problem with the Kucoin API is that the size field cannot be sent as decimal in PlaceOrderAsync because this field is considered as integer in their API documentation.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/72021670/146171943-9970c7dd-808b-4a88-8c26-603f78c3d204.png)
> 
> 
> 
> For example, you can't trade Bitcoin because it requires at least $ 50,000
> 
> Is there a solution to this problem?

We need to report this to Kucoin Support

**Comment by shahrooztk** [comment]
Hello friends. 
I was also involved with this problem in the beginning. But the way this exchange works, unlike other exchange offices like Binance, is not based on the amount of purchase.
In Kucoin, size based on like a "Lot". (Like as Forex).
As a result, if you want to buy in decimal and value, You need to create a code and formula that will convert your value into a Lot and send integer to open and close orders.

**Comment by hyperms** [comment]
> Hello friends. I was also involved with this problem in the beginning. But the way this exchange works, unlike other exchange offices like Binance, is not based on the amount of purchase. In Kucoin, size based on like a "Lot". (Like as Forex). As a result, if you want to buy in decimal and value, You need to create a code and formula that will convert your value into a Lot and send integer to open and close orders.

Can you explain with an example?

**Comment by hyperms** [comment]
> Hello friends. I was also involved with this problem in the beginning. But the way this exchange works, unlike other exchange offices like Binance, is not based on the amount of purchase. In Kucoin, size based on like a "Lot". (Like as Forex). As a result, if you want to buy in decimal and value, You need to create a code and formula that will convert your value into a Lot and send integer to open and close orders.

Yes, you were right
Thanks
