### ISSUE TITLE
Two things about SubscribeToStopOrderUpdatesAsync method

### ISSUE THREAD

**Issue by shahrooztk** [JKorf/Kucoin.Net#101]
Hi @JKorf again
There is a small case in the socket method "SubscribeToStopOrderUpdatesAsync" that I think should be corrected.

First is it possible merge "SubscribeToStopOrderUpdatesAsync" with "SubscribeToOrderUpdatesAsync" ? 
I think these two are one, it is better to receive and process information together in one method.

Secondly, I think it is a problem that the OrderType property in this method is "string" type and I think it is better to use enum KucoinMatchUpdateType type.

Thanks.

**Comment by shahrooztk** [comment]
I realized another thing.
In Kucoin futures , when I put the price on the market , No events are executed in "SubscribeToStopOrderUpdatesAsync" method. But when price are limit this method is execute.


![image](https://user-images.githubusercontent.com/23153570/147385009-ca318d43-a395-4eae-ae33-604363fd532a.png)

**Comment by JKorf** [comment]
Cleaning up old issues, assuming this issue is no longer relevant

To answer the original comment; they are 2 different subscriptions on the API so it's better to offer them seperately to the user. I also think all relevant string fields are now enums.
