### ISSUE TITLE
Expiry/Delivery Date of a Futures Contract

### ISSUE THREAD

**Issue by danielhw2** [JKorf/Kucoin.Net#103]
How can I get the Expiry/Delivery Date of a specific future contract using Kucoin.net?
I'm using the GetOpenContractsAsync() and GetContractAsync(), but those don't give the date for the contracts.
ie: "XBTMH22"

Thanks =)

**Comment by JKorf** [comment]
This wasn't documented but when updating the GetOpenContractsAsync model based on the actually returned data it turns out that it is returned there. It is available in the latest version
