### ISSUE TITLE
KucoinClientFutures.CancelAllOpenOrdersAsync ignores symbol param and closes all open orders

### ISSUE THREAD

**Issue by TylerDelmus** [JKorf/Kucoin.Net#104]
Problem: KucoinClientFutures.CancelAllOpenOrdersAsync cancels all open orders regardless of the presence of a symbol param.

Fix: Per the Kucoin Futures API documentation the symbol param should be passed as a query param and not in the body.

https://docs.kucoin.com/futures/#limit-order-mass-cancelation

DELETE /api/v1/orders?symbol=XBTUSDM

**Comment by JKorf** [comment]
This should be fixed in the latest versions
