### ISSUE TITLE
How to set the cancelAfter field in Limit Order Parameters

### ISSUE THREAD

**Issue by mohammad-arad** [JKorf/Kucoin.Net#108]
In the placeorder method, it is possible to set the cancellation time as cancelAfter to record the limit order, but it seems that this method is not implemented.

**Comment by JGronholz** [comment]
Nothing in code stands out. Please verify that you are using TimeInForce.GoodTillTime when placing the order.

What doesn't happen that should?
What does happen that shouldn't?
