### ISSUE TITLE
4.0.0.0-beta1 / SubscribeToStopOrderUpdatesAsync does not receive any updates

### ISSUE THREAD

**Issue by cwolters** [JKorf/Kucoin.Net#109]
In the 4.0.0.0-beta1, I do not receive any events regarding stop orders.

*  register listener -> kucoinClient.FuturesStreams.SubscribeToStopOrderUpdatesAsync(onStopOrderUpdate)
* log seems to subscribe, but no events are emitted.
```
Kucoin     | Socket 1 sending data: {"id":"12","type":"subscribe","topic":"/contractMarket/advancedOrders","privateChannel":false,"response":true}
Kucoin     | Socket 1 Adding 110 to sent buffer
Kucoin     | Socket 1 sent 110 bytes
Kucoin     | Socket 1 received 24 bytes in single message
Kucoin     | Socket 1 received data: {"id":"12","type":"ack"}
```

Could it be, that the "privateChannel":false cause the problem?
The trade orders are received after subscription and it only differes in the "privateChannel":true value.
```
Kucoin     | Socket 1 sending data: {"id":"10","type":"subscribe","topic":"/contractMarket/tradeOrders","privateChannel":true,"response":true}
Kucoin     | Socket 1 Adding 106 to sent buffer
Kucoin     | Socket 1 sent 106 bytes
Kucoin     | Socket 1 received 24 bytes in single message
Kucoin     | Socket 1 received data: {"id":"10","type":"ack"}
```

**Expected behavior**
Submitted, executed or cancelled stop orders should result in the onStopOrderUpdate-method called.

I created a pull request for the changes - but I could not test it on my side: https://github.com/JKorf/Kucoin.Net/pull/110

**Comment by cwolters** [comment]
btw. Same problem seems to be with SubscribeToBalanceUpdatesAsync - no updates are received on my side.

```
Kucoin     | Socket 1 sending data: {"id":"5","type":"subscribe","topic":"/contractAccount/wallet","privateChannel":false,"response":true}
Kucoin     | Socket 1 Adding 102 to sent buffer
Kucoin     | Socket 1 sent 102 bytes
Kucoin     | Socket 1 received 23 bytes in single message
Kucoin     | Socket 1 received data: {"id":"5","type":"ack"}
```

**Comment by JKorf** [comment]
Hi, I see you made a PR for this, but I already fixed it when I saw your initial message so I'll close the PR. Version beta2 should work again. Let me know if you find anything else!

**Comment by cwolters** [comment]
Works as well! Top!
