### ISSUE TITLE
GetTickersAsync; Error converting value {null} to type 'System.Decimal'

### ISSUE THREAD

**Issue by Bigrichardo** [JKorf/Kucoin.Net#11]
The next error comes in the Output when the method GetTickersAsync() is used.
Error | Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'data.ticker[228].changePrice', 

It cant process any information now.

**Comment by JKorf** [comment]
I guess that can happen when a new symbol comes online and there is no change yet. I've made the decimals nullable so it should work if a new symbol is added next time.
Thanks for the report!

**Comment by Bigrichardo** [comment]
Je bent nederlands toch?
Echt puik werk hoor.
Ik heb het altijd zelf gebouwd, maar dit maakte het wel heel makkelijk. Wat
doe je verder voor de kost?

Op ma 20 jul. 2020 12:18 schreef Jan Korf <notifications@github.com>:
