### ISSUE TITLE
v.3.2.1 - client.Futures.PlaceOrderAsync. Error "100000: JSON parse error: Cannot deserialize value of type `java.lang.Integer` from String "0.001": not a valid Integer value;"

### ISSUE THREAD

**Issue by ROMAN5** [JKorf/Kucoin.Net#115]
client.Futures.PlaceOrderAsync(string symbol, KucoinOrderSide side, KucoinNewOrderType type, int leverage, decimal size.....

symbol = "XBTUSDTM"
side = KucoinOrderSide.Buy
type = KucoinNewOrderType.Market
leverage = 50
size = 0.001

Error message is "100000: JSON parse error: Cannot deserialize value of type `java.lang.Integer` from String "0.001": not a valid Integer value;"

:-(

**Comment by JKorf** [comment]
Quantity should be an integer. Kucoin specifies the quantity in contracts, not in BTC or USD

**Comment by ROMAN5** [comment]
Great. You are right. It is working. Thank you very much!
