### ISSUE TITLE
'OrderSide' is an ambigous reference...

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Kucoin.Net#116]
Hi,
I am using version 4.0.0-beta4.
I am getting the following error for 'OrderSide' when I want to submit a new order order. I also use your Binance.Net library, but I have not encountered such an error there.

![Adsız](https://user-images.githubusercontent.com/7556164/150542517-0e7f781e-d102-4d2d-97a8-d71dca4b92dc.png)

**Comment by JKorf** [comment]
Hi, I've updated the common enum names with a Common- prefix, so this should be resolved with the latest version
