### ISSUE TITLE
PlaceOrderAsync  Error 400100: validation.createOrder.clientOidDuplicated

### ISSUE THREAD

**Issue by allcasper99** [JKorf/Kucoin.Net#120]
Hello,
When I use the PlaceOrderAsync method, I get an error as attached. I look forward to your help in this matter.

![kucoingithub](https://user-images.githubusercontent.com/77941443/154330560-ecd6e8e9-cafe-4278-9016-76e699175342.png)

**Comment by JKorf** [comment]
The clientOrderId you provide has already been used before. The clientOrderId parameter should be unique for each order

**Comment by allcasper99** [comment]
thank you sir. I thought the client id was the trade password. Now I generate a random number and send it. The process runs smoothly
