### ISSUE TITLE
PlaceOrderAsync,  not work with Market - CRITICAL BUG

### ISSUE THREAD

**Issue by heavymanto** [JKorf/Kucoin.Net#121]
**Describe the bug**
Market place order raise an Exception of miss amount but is set
![image](https://user-images.githubusercontent.com/6449169/155855157-473005fd-e0da-4d71-9e0f-e169e4a0d7ae.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/6449169/155855149-0680a422-5c63-4173-9901-8a2d9afefa1b.png)

**Comment by heavymanto** [comment]
I have study last version and found bug. There is a reverse o quantity and price argoments passed from ISpotClient.PlaceOrderAsync to  Trading.PlaceOrderAsync

![image](https://user-images.githubusercontent.com/6449169/155878681-b86a50d9-e843-48ae-a780-e70bc15be59f.png)

**Comment by heavymanto** [comment]
furthermore, a test is missing if the price is non-null in the limit case. A limit order must have both price and quantity

![image](https://user-images.githubusercontent.com/6449169/155878828-9809e924-0db3-4a48-800f-343946d0cfe3.png)

**Comment by JKorf** [comment]
Hi, you're right. This is a serious bug. I've released an update where this is fixed, thanks for the report and analysis

**Comment by heavymanto** [comment]
ok, now it work fine! Thank for your "speed relaed".
