### ISSUE TITLE
Endpoint for Margin Acocounts

### ISSUE THREAD

**Issue by bogdanovap** [JKorf/Kucoin.Net#122]
Hello!
Can not find endpoints for getting info on Margin Account. Please, give a hint.
Here are the endpoints I am looking for:
GET /api/v1/margin/config
GET /api/v1/margin/account
GET /api/v1/risk/limit/strategy

**Comment by JKorf** [comment]
Hi, these endpoints weren't available yet, but I've added them in the latest version

**Comment by bogdanovap** [comment]
Thanks!
