### ISSUE TITLE
Using TestNet

### ISSUE THREAD

**Issue by maysamsh** [JKorf/Kucoin.Net#123]
I am trying to use TestNet but I'm not sure if I'm doing it right:

```
var kucoinClient = new KucoinClient(new KucoinClientOptions()
            {
                ApiCredentials = new KucoinApiCredentials("", "", ""),
                LogLevel = LogLevel.Trace,
                RequestTimeout = TimeSpan.FromSeconds(60),
                SpotApiOptions = new KucoinRestApiClientOptions()
                {
                    BaseAddress = "https://openapi-sandbox.kucoin.com/api/"
                }
            }); ; ; ;
```

Is it the right way to create the client?

**Comment by JKorf** [comment]
Yes that's fine. Alternatively you can use `BaseAddress = KucoinApiAddresses.TestNet.SpotAddress` but it resolves to the same

**Comment by maysamsh** [comment]
@JKorf when I use the TestNet and put an order I receive:
`504000: Gateway Timeout %   `

**Comment by maysamsh** [comment]
I was using production credentials.
