### ISSUE TITLE
Repaying a borrowed order

### ISSUE THREAD

**Issue by jakebayliss** [JKorf/Kucoin.Net#124]
Repaying a borrow order doesn't actually seem to repay the order, however, is returning a Success code?

```
var repayOrder = await _client.SpotApi.Trading.RepaySingleBorrowOrderAsync(borrowOrder.Data.Asset, borrowOrder.Data.Id, borrowOrder.Data.Quantity);
if (repayOrder.Error != null)
{
    throw new Exception(marketOrder.Error.Message);
}
```

![274233800_357457299572897_7054935996890645492_n](https://user-images.githubusercontent.com/32888060/156505215-f1353aea-9dcc-47ca-a11c-119498448fa8.png)

**Comment by JKorf** [comment]
Hm that's weird. This is what the API docs say:
`A successful repayment response is indicated by an HTTP status code 200 and system code 200000. If the system returns other code, it means the repayment fails.`
The Http status code is 200 OK and if the result system code is anything other than 200000 the library will return an error, so it seems like the server just returned a success response.
You could verify the response the server sends by setting LogLevel to Trace in the client options and see what the server returns in the log output, but again, it seems like the server indicates success.
