### ISSUE TITLE
KucoinApiAddresses - Usage

### ISSUE THREAD

**Issue by jimtollan** [JKorf/Kucoin.Net#125]
Hi there. First off, love both Kucoin.Net and Binance.Net. Can't imagine ever rolling my own shoddy implementations again.

Quick question tho as this one is causing me a few issues. I've got a sandbox account and would like to switch to the KucoinApiAddresses.TestNet environment. However, I just cannot figure where exactly I make this change in my code as I can't find reference in the docs. I'm sure it's super simple and must be at the level of adding authentication, but no inspiration pushing out at me.

How do I make this change?? I've got my sandbox api keys and am good to go, but wondered where the magic happens.

Cheers -hope you can help.
jim

**Comment by JKorf** [comment]
Hi, thanks for the kind words.
You can switch to the sandbox environment by changing the BaseAddress in the client options. In the latest version that would be like this: 
````csharp
var kucoinClient = new KucoinClient(new KucoinClientOptions()
{
    SpotApiOptions = new KucoinRestApiClientOptions
    {
        BaseAddress = KucoinApiAddresses.TestNet.SpotAddress
    }
});
````

**Comment by jimtollan** [comment]
ok, thanks for that... plugged that in to the Futures implementation and got a small error when pulling back the data. it says that it can't find the URL: https://openapi-sandbox.kucoin.com/api/v1/account-overview

I'm using:  _clientFutures.FuturesApi.Account.GetAccountOverviewAsync();

Hopefully a straightfwd issue to figure out (maybe the version number on the sandbox has changed??)

cheers for the quick response.
jim

**Comment by jimtollan** [comment]
![image](https://user-images.githubusercontent.com/87867061/156776926-97fe226d-38db-4fa0-a2c9-90fd89bad245.png)

**Comment by JKorf** [comment]
For the futures API you should change the address to `KucoinApiAddresses.TestNet.FuturesAddress` instead of SpotAddress

**Comment by jimtollan** [comment]
> For the futures API you should change the address to `KucoinApiAddresses.TestNet.FuturesAddress` instead of SpotAddress

of course - doh!! :D

**Comment by jimtollan** [comment]
sorry - i have another small issue on Futures. I know i should start a new thread, but just in case it's related, thought i'd put it here. I've created an order on futures which all went fine and am attempting to add a stoploss below the bought price. However, I'm getting an error stating that i've omitted the *price* info. As you can see from the debug message, the price is actually being supplied:

![image](https://user-images.githubusercontent.com/87867061/156794813-f9d1e583-e504-4888-8b92-66876a16003d.png)

Below also is some quick 'n dirty code that i used to test the order and stop (ignore the fact that i'm bypassing the async await for now ;)):

![image](https://user-images.githubusercontent.com/87867061/156795486-f702614f-a65a-4042-ba01-bde59864a34d.png)

If there's anything weird looking, please point it out to me -i'm staring at it too much to catch it!! 

thanks again

**Comment by JKorf** [comment]
You're setting the `price` parameter, however you need the `stopPrice` parameter. The `price` parameter is the price of the order you're placing (which you don't need since it's a market order), the `stopPrice` is the trigger price.

**Comment by jimtollan** [comment]
> You're setting the `price` parameter, however you need the `stopPrice` parameter. The `price` parameter is the price of the order you're placing (which you don't need since it's a market order), the `stopPrice` is the trigger price.

gotcha - every day's a sk00L day
