### ISSUE TITLE
Deserialization Error

### ISSUE THREAD

**Issue by mmazloom** [JKorf/Kucoin.Net#126]
**Describe the bug**
when I call the GetOrderAsync method (using spot API) with a valid order Id, like this:
var callResult = await kucoinClient.SpotApi.Trading.GetOrderAsync(txtOrderID.Text);

I get the following error:
: Deserialize JsonSerializationException: Error setting value to 'Stop' on 'Kucoin.Net.Objects.Models.Spot.KucoinOrder'. [Data only available in Debug LogLevel]

**Comment by JKorf** [comment]
Hi, are you using the latest version?

**Comment by mmazloom** [comment]
Thank you for the reply. 
I have installed the latest nuget package for my win form application with 4.6 framework.

**Comment by allcasper99** [comment]
were you able to solve the problem?
