### ISSUE TITLE
GetKlinesAsync sometimes throws unhadled exception.

### ISSUE THREAD

**Issue by kv-gits** [JKorf/Kucoin.Net#127]
With this code I download periodically historical data. 
```
public async Task<List<Ohlcv>> GetKlines(string symbol, DateTime lt, DateTime rt)
        {
            List<Ohlcv> l = new();
            CryptoExchange.Net.Objects.WebCallResult<IEnumerable<Kucoin.Net.Objects.Models.Spot.KucoinKline>> data;
            try
            {
                data = await client.SpotApi.ExchangeData.GetKlinesAsync(symbol, KlineInterval.OneMinute, lt, rt);
            }
            catch (Exception e)
            {
                Console.WriteLine("Exception: {0}", e);
                return null;
            }
            if (data == null)
            {
                return null;
            }
...
...
...
}
```
But sometimes server returns 
`{"code":"429000","msg":"Too Many Requests"}` even if I send request rarely, near 1 at 90 seconds.
And exceptions throwed
System.AggregateException: 'One or more errors occurred. (Value cannot be null. Arg_ParamName_Name)' And it is unhandled and stops program but just need to wait 5 minutes.

**Comment by JKorf** [comment]
I can't reproduce this, are you sure you're not accidentally passing in null somewhere? Could you maybe share the stacktrace of the exception?
