### ISSUE TITLE
There are problems in the latest version

### ISSUE THREAD

**Issue by allcasper99** [JKorf/Kucoin.Net#128]
Hello,

I am encountering errors in the latest version of the app. As an example below, I am trying to pull the order that I have made according to the orderid. i am getting error. Everything was fine in the previous version.

![kucoingithub2](https://user-images.githubusercontent.com/77941443/157493810-90aed11b-6943-4c59-ab1d-fe43632b5d2c.png)

I can see the funds in my account. Other than that, I can't order or see.
I am using NETFramework,Version=v4.7.2

**Comment by allcasper99** [comment]
I can see the funds in my account. Other than that, I can't order or see.
I am using NETFramework,Version=v4.7.2

**Comment by WideAngleDev** [comment]
Having the same issue when pulling the order via GetOrderAsync.
The issue is in 4.0.3 and latest 4.0.4 version as well.

**Comment by JKorf** [comment]
Thanks for the reports, I'm working on it. Issue should be fixed somewhere tomorrow

**Comment by JKorf** [comment]
Hi, version 4.0.5 should have this fixed, let me know if you have any (other) issues.

**Comment by WideAngleDev** [comment]
Fix is working perfectly. You're doing a great job with these wrappers! A big thank you! :)

**Comment by JKorf** [comment]
Great, thanks for the kind words :)

**Comment by allcasper99** [comment]
Thank you sir. i will try right away
