### ISSUE TITLE
Puzzled by setting order Size on futures

### ISSUE THREAD

**Issue by jimtollan** [JKorf/Kucoin.Net#129]
Hi there - got a small issue which could be down to my understanding of how to work with the various parameters required for creating a Futures order. On reading the documents, it would appear that i must first query the Contract in order to get the metadata related to min/max leverage allowed, plus data related to the Multiplier used. on querying this data, i receive a payload that has all of this metadata : 

// symbol = "UNIUSDTM"
` var contract = await _clientFutures.FuturesApi.ExchangeData.GetContractAsync(symbol);`

all good. However, I'm not entirely sure which data elements I should use as I've been getting varied results when applying the Multiplier found in the contract data. Below is my crude attempt to calculate the resulting size required for a fixed currency amount:

// dollarFunds =100m
// bidPrice = 95.6
`quantity = (dollarFunds / bidPrice / (contract.Data.Multiplier * leverageRate));`

I also tried the simpler version of the below which worked in some cases, but like the other version, not all:

`quantity = (dollarFunds / bidPrice * leverageRate);`

I then use it as thus:

```
var orderBuy = await _clientFutures.FuturesApi.Trading.PlaceOrderAsync(
    symbol,
    orderSideAdd,
    Kucoin.Net.Enums.NewOrderType.Limit, leverageRate, quantity, bidPrice,
    Kucoin.Net.Enums.TimeInForce.GoodTillCanceled, remark: remark);
```

The above calc is obviously way wrong as it is fine for some contracts and wildly out for others.

I feel such an idiot, but what on earth am I doing wrong (either in terms of logic, or in terms of the data I'm using).

This is the final piece in a nice little leverage play that I've been working on successfully with minimum contract size, the missing puzzle piece now comes when applying hard scalable $$.

Hope you can help.
jim

**Comment by jimtollan** [comment]
fyi - i've added a question on SO to see if anyone has got a take on how this SIZE calculation operates: https://stackoverflow.com/questions/71570861/kucoin-futures-calculating-order-size

**Comment by jimtollan** [comment]
I figured it out. it was down to using the Multiplier in a particular *way* ;)

            quantity = Math.Round((dollarFunds / bidPrice * (leverageRate / contract.Data.Multiplier)),
                decimalPlaces, MidpointRounding.AwayFromZero);

hope this helps someone else. will add more detail later.

**Comment by doubtrageous** [comment]
I appreciate you taking the time to post your findings. Seems info on this is still pretty limited. A question was posted on the KuCoin subreddit that is along the same lines and it was sadly pretty much ignored. It's about confusion regarding this "size" parameter for level 2 and executed trades calls/sockets. Any insight you could pass along would be greatly appreciated.

https://www.reddit.com/r/kucoin/comments/tns1x2/could_someone_please_help_me_understand_how_the/

**Comment by doubtrageous** [comment]
Sometimes you just gotta go with what works in the moment. Good work on getting it rolling and appreciate the additional info. I contacted the KuCoin API dev team and for posterity and any future folks here's what I got:

```
SIZE
The size must be no less than the lotSize for the contract and no larger than the maxOrderQty. It should be a multiple number of lotSize, or the system will report an error when you place the order. Size indicates the amount of contract to buy or sell. Size is the number or lot size of the contract. Eg. the lot size of XBTUSDTM is 0.001 Bitcoin, the lot size of XBTUSDM is 1 USD.

"lotSize": 1,
"multiplier": 

All 1 is normal, because there is a multiplier field.

so the order value = lotSize * multiplier

We have to add more explanation about this to help doc  which we will do soon
```

**Comment by jimtollan** [comment]
> Sometimes you just gotta go with what works in the moment. Good work on getting it rolling and appreciate the additional info. I contacted the KuCoin API dev team and for posterity and any future folks here's what I got:
> 
> ```
> SIZE
> The size must be no less than the lotSize for the contract and no larger than the maxOrderQty. It should be a multiple number of lotSize, or the system will report an error when you place the order. Size indicates the amount of contract to buy or sell. Size is the number or lot size of the contract. Eg. the lot size of XBTUSDTM is 0.001 Bitcoin, the lot size of XBTUSDM is 1 USD.
> 
> "lotSize": 1,
> "multiplier": 
> 
> All 1 is normal, because there is a multiplier field.
> 
> so the order value = lotSize * multiplier
> 
> We have to add more explanation about this to help doc  which we will do soon
> ```

well, if you happen to arrive at a nice little extension method or extended library that works against the Kucoin.Net library, then ping me the link if you share it. My version is definitely pretty ropey and too embarrassing to publicly expose!
