### ISSUE TITLE
GET /api/v1/currencies/{currency} - missing optional parameter "chain"

### ISSUE THREAD

**Issue by masherak** [JKorf/Kucoin.Net#130]
Hello @JKorf , please is it possible to add optional parameter ChainId to the endpoint below? Thank you for your response!

<img width="730" alt="image" src="https://user-images.githubusercontent.com/15813908/159140842-c6349f5d-5065-42e5-83b1-25db7ef1a60f.png">

**Comment by JKorf** [comment]
Hi, the library uses the V2 version, which already returns info on the chains

**Comment by masherak** [comment]
I can see changes in the 4.0.4 version, I had 4.0.3. Thank you very much
