### ISSUE TITLE
Error System.NullReferenceException on CommonFuturesClient.PlaceOrderAsync

### ISSUE THREAD

**Issue by deewelop** [JKorf/Kucoin.Net#133]
so this is my code:

```
//--> futures is (KucoinClient.FuturesApi.CommonFuturesClient)

var res_ = await futures.PlaceOrderAsync
(
    me.symbol,    //ETHUSDT
    (CommonOrderSide)side1,    //CommonOrderSide.Sell
    CommonOrderType.Market,    
    Math.Round(me.size, me.QuDecimal), //14
    null,    //its price, cus im using market, its null
    (int)me.zarib   //leverage is 12
);
```

and this is error:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

and screenshot:
![image](https://user-images.githubusercontent.com/86514539/160090032-6af06e32-5bc4-4275-8138-cad19f9d3a98.png)

any help pls? <3

**Comment by deewelop** [comment]
its same problem i guess, just mine is for futures...
#121

**Comment by deewelop** [comment]
@JKorf @heavymanto

**Comment by deewelop** [comment]
Thanks a LOT <3

**Comment by deewelop** [comment]
sorry again have other problem, now with that code i'm always get error on place order (in kucoin):
"error.createOrder.timeInForceInvalid"

there is not any parameter named "timeInForce" in (CommonFuturesClient).PlaceOrderAsync method to be invalid ...
@JKorf i'm 2 weeks on this stuck problem, a little more help pls <3

**Comment by deewelop** [comment]
and now its 4 weeks :(
help pls <3
can't develop my app till this problem not solved

**Comment by heavymanto** [comment]
Test with another Exchange (es Binance). I have left Kucoin for its problem

Il Gio 21 Apr 2022, 11:05 Javad Gholizadeh ***@***.***> ha
scritto:

**Comment by deewelop** [comment]
project if not just for myself, And best joint exchange between us is kucoin so can't change broker :(
if this problem found and fixed i'm done 
a little help pls, what's problem?

**Comment by deewelop** [comment]
i will test last version, thanks a lottt <333
and no i'm using multi brokers (binance, kucoin, ...), but kucoin is one of require ones

by the way, your this exchanges api projects are perfect, specially this common api, make working with multi broker a lot lot easier... <3
my income is not much going up yet, but if and when things works, i will definitely support as sponser
thanks again... <3
