### ISSUE TITLE
GetKlinesAsync 15 minutes timespan

### ISSUE THREAD

**Issue by jpellouchoud** [JKorf/Kucoin.Net#136]
**Describe the bug**
When calling "SpotApi.CommonSpotClient.GetKlinesAsync" using a 15 minute timespan, It returns the 5 minute timespan list.

**To Reproduce**
SpotApi.CommonSpotClient.GetKlinesAsync("BTC-USDT", TimeSpan.FromMinutes(15));

**Expected behavior**
A listed of Klines with a 15 minute timespan.

**Comment by JKorf** [comment]
Thanks for the report, there was a typo there. It's fixed in the latest version
