### ISSUE TITLE
GetKlineAsync  retrieves only 100 klines when startTime = null

### ISSUE THREAD

**Issue by WideAngleDev** [JKorf/Kucoin.Net#138]
**Describe the bug**
When I call GetKlineAsync with startTime = null i recieve only 100 klines.  Is this a new behaviour? 
When I checked my dumped bot backtests, it seems that the behaviour changed around 15.3.2022.
Before this date I recieved proper count of klines, after 15.3.2022 including, i got only 100 klines.

**To Reproduce**
Task<WebCallResult<IEnumerable<KucoinKline>>> klinesTask = null;
            WebCallResult<IEnumerable<KucoinKline>> klines = null;
            klinesTask = client.SpotApi.ExchangeData.GetKlinesAsync(symbol: "BTC-USDT", interval: Kucoin.Net.Enums.KlineInterval.OneDay, startTime: null, endTime: DateTime.Now);
            klines = klinesTask.Result;
            Console.WriteLine("klines retrieved:"  + klines.Data.Count());

**Expected behavior**
When startTime = null the request should return the maximal allowed limit of the klines. (probably Kucoin changed to only 100???)

**Comment by JKorf** [comment]
I don't see any mention of this on the Kucoin API documentation, but I'm guessing they've changed it then yes

**Comment by WideAngleDev** [comment]
Hi me too. I havent found anything about the restriction. Funny thing is that it already seems to be working as expected again. I'm a bit confused about this, however I didn't have time to investigate deeper. I'll try next days. Anyway thank you!
