### ISSUE TITLE
Deserialize issue on GetRecentUserTradesAsync

### ISSUE THREAD

**Issue by devfxplayer** [JKorf/Kucoin.Net#142]
[GetRecentUserTradesAsync] not found 626135407cb821000148b62d, Error: : Deserialize JsonSerializationException: Error setting value to 'Stop' on 'Kucoin.Net.Objects.Models.Spot.KucoinUserTrade'. [Data only available in Debug LogLevel]

When built for release I get this error. When I debug I don't get it.

**Comment by JKorf** [comment]
Seems like somehow your release version still works with an older version of the library where that issue was present

**Comment by devfxplayer** [comment]
ok thanks
