### ISSUE TITLE
Set Take Profit And Stoploss

### ISSUE THREAD

**Issue by dilancoder** [JKorf/Kucoin.Net#143]
Hi Guys
I want to set TakeProfit And Stoploss(Futures) for a Limit order

Can anyone help me?

**Comment by pahager** [comment]
Hi, did you find any solution?

**Comment by dilancoder** [comment]
> Hi, did you find any solution?
No, this fucking repository has no support

**Comment by JKorf** [comment]
This "fucking library" supports all endpoints offered in the API, though there might be something missing somewhere. The question of "how to set TakeProfit/StopLoss" is not really a question about or issue with this library, but rather a question on how to use the API
