### ISSUE TITLE
Timestamp Problem in KlineUpdates

### ISSUE THREAD

**Issue by MrSinor** [JKorf/Kucoin.Net#145]
**To Reproduce**
I'm using `SubscribeToKlineUpdatesAsync` from SpotStreams **(OneMinute Interval)** and control updates using `OnKlineUpdate(DataEvent<KucoinStreamCandle> obj)` function to get [Klines](https://docs.kucoin.com/#klines).

**Describe the bug**
Sometimes `obj.Timestamp` inside `OnKlineUpdate` function is out of the candle time range.
For example `obj.Data.Candles.OpenTime` is `23:10:00` and because of OneMinute Interval close time will be `23:11:00`
In this case, `Timestamp` in `obj` variable is `23:11:01` or `23:11:02`.

If `Timestamp` value is out of the candle time range it will cuase many problems in calculations.
**This problem exist in other intervals, not only for OneMinute.**

**Expected behavior**
`Timestamp` should be greater than `obj.Data.Candles.OpenTime` and smaller than or equal to `obj.Data.Candles.OpenTime + Interval`.

**Debug logging**
@JKorf please Pay attention to this screenshot of recived data. Bug highlighted blue:
![Screenshot](https://user-images.githubusercontent.com/20723864/165596226-44b74cce-f45f-4b19-a25c-3c62f98265b0.png)

**Comment by JKorf** [comment]
Hi, this is something on the server side. I guess it can happen that an update is slightly late and is still for the candle which has just passed. You should use the Candle OpenTime as reference, not the timestamp you receive the data
