### ISSUE TITLE
Stop Order cant see by GetOrdersAsync()

### ISSUE THREAD

**Issue by Dimasio7777** [JKorf/Kucoin.Net#149]
var stopLossResult = await Kucoin.FuturesApi.Trading.PlaceOrderAsync(FutTrPair, Kucoin.Net.Enums.OrderSide.Sell, NewOrderType.Limit, Leverage, quantity: 0, price: SL, timeInForce: Kucoin.Net.Enums.TimeInForce.GoodTillCanceled, stopType: StopType.Down, stopPriceType: StopPriceType.MarkPrice, stopPrice: SL, closeOrder: true);
           
After its shows in Kucoin Orders list as Stop Order.

I use
   var result = await kucoinclient.FuturesApi.Trading.GetOrdersAsync(FutTrPair, Kucoin.Net.Enums.OrderStatus.Active);
And i cant see my order. Its only show Limit orders(working good!). For Stop order its not working.

**Comment by JKorf** [comment]
I think you'd have to request stop orders with GetUntriggeredStopOrdersAsync
