### ISSUE TITLE
Issue: FuturesApi.CommonFuturesClient.GetSymbolsAsync()

### ISSUE THREAD

**Issue by jimtollan** [JKorf/Kucoin.Net#151]
Hi there... it would appear that Kucoin are being naughty and are sending out some data that contains nulls which is preventing the Kucoin implementation from working. When issuing the above command, I'm getting the following error:

Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'data[110].openInterest', line 1, position 150420.

I've tracked this down to the removal of the LUNAUSDTM entry and found that the following value is being set => 
"openInterest":null,

Do you know if there's a workaround that doesn't require a recompile of the core code??

Cheers
jim

hitting the url in the browser: https://api-futures.kucoin.com/api/v1/contracts/active shows the error when we search for **"openInterest":null** Hope this helps..

**Comment by JKorf** [comment]
I've made it nullable in the latest version, which should fix this issue
