### ISSUE TITLE
error in kline

### ISSUE THREAD

**Issue by yosef228** [JKorf/Kucoin.Net#152]
Hi dear jkorf
GetklinesAsync returns only candles that their trade volume is above 0 !!
And this error causes my calculations like the RSI indicator to be incorrect.

I use this code:
var kline = await Futureclient.FuturesApi.CommonFuturesClient.GetKlinesAsync(symb, TimeSpan.FromMinutes(1));

**Comment by JKorf** [comment]
This is not an issue with this library, but rather with the API. Not much I can do about that
