### ISSUE TITLE
Future API not work

### ISSUE THREAD

**Issue by vatttanweb** [JKorf/Kucoin.Net#153]
When I call Future API for placing order I get this error:
`Service not available temporarily, please try it later.`

**Comment by JKorf** [comment]
I don't see this error. Have you changed the base address?

**Comment by vatttanweb** [comment]
> 

Not at all. Just I call your package like this:
`var client = new KucoinClient(new KucoinClientOptions()
            {

                ApiCredentials = new KucoinApiCredentials("629eccafc437540001f61f48",

                "889c85d7-78a1-4e7f-912b-973d5e0a618c", "Aa@2232610"),

                LogLevel = LogLevel.Trace,

                RequestTimeout = TimeSpan.FromSeconds(60),
                FuturesApiOptions = new KucoinRestApiClientOptions
                {
                    ApiCredentials = new KucoinApiCredentials("629d81337c7240000110b232",
                    "e9a0fff9-37a0-4d4e-894b-390017eef597", "Aa@123456"),
                    AutoTimestamp = false
                }
            });
            var result = client.FuturesApi.Trading.PlaceOrderAsync("ETH Perpetual/USDT",
Kucoin.Net.Enums.OrderSide.Buy, NewOrderType.Limit, 1, 2, 4).Result;`

**Comment by JKorf** [comment]
Please don't share you credentials. I've edited them out, but you should change your keys asap since they've been public and people might access your account

**Comment by JKorf** [comment]
On topic; the issue is probably in your symbol. Try ETHUSDT instead

**Comment by vatttanweb** [comment]
Thanks for your edit but with this symbol name that you said I get this error:
`100003: Contract parameter invalid `

**Comment by JKorf** [comment]
Sorry, should be `ETHUSDTM`

**Comment by vatttanweb** [comment]
Yessssss. Thanks a lot Sir.
