### ISSUE TITLE
Kucoin Futures Sandbox not filling the orders

### ISSUE THREAD

**Issue by wilsonsuryajaya** [JKorf/Kucoin.Net#156]
Hi,

I am able to use Kucoin .NET to place and cancel orders on the futures sandbox environment `(BaseAddress = TestNet.FuturesAddress)` and also able to receive the open orders from `GetOrdersAsync(OrderStatus.Active)`. Now I am trying to test the trade and position related functions but the futures sandbox environment doesn't seem to fill any of the orders. 

**Attempt 1**: Placed a market order of 1 contract for XBTUSDTM
It came back with: _"Order canceled Buy 1 BTC Perpetual/USDT contract(s) at market price, caused by: Not contra orders in the specified price range"_

**Attempt 2**: Tried matching my own orders by placing a long limit order at a high price, followed by a short limit order at a lower price. Both orders appeared successfully as open orders but no trade was generated.

**Account Details** using `kucoinClient.FuturesApi.Account.GetAccountOverviewAsync()`
Asset: USDT
AvailableBalance: 5475.31
AccountEquity: 5500
UnrealizedPnl: 0
MarginBalance: 5500
PositionMargin: 0
OrderMargin: 24.694
FrozenFunds: 0

I wonder if anyone had the same experience before?

Thanks

**Comment by JKorf** [comment]
Based on the message I'd say there isn't enough liquidity to match your orders on the sandbox environment. Not much I can do about that unfortunately
