### ISSUE TITLE
CreateDepositAddressAsync Error Invalid chainId [900014]

### ISSUE THREAD

**Issue by samanbahrekazemi** [JKorf/Kucoin.Net#158]
**Describe the bug**

**To Reproduce**
What endpoints and subscriptions are called.

**Expected behavior**

**Debug logging**
Add debug logging related to the issue. Enable Debug logging in the client options by settings LogLevel to Debug.

**Comment by samanbahrekazemi** [comment]
this method return an error [code: 900014] Invalid ChainId by this parameters [symbol="ETH",netwoek="TRC20"]

**Comment by JKorf** [comment]
I don't know if there is support for alternative ETH networks, the parameter description on the docs say this:

[Optional] The chain name of currency, e.g. The available value for USDT are OMNI, ERC20, TRC20, default is ERC20. The available value for BTC are Native, Segwit, TRC20, the parameters are bech32, btc, trx, default is Native. This only apply for multi-chain currency, and there is no need for single chain currency.

**Comment by samanbahrekazemi** [comment]
Thank's for your help, but I try the ["https://www.kucoin.com/_api/currency/currency/chain-info"](https://www.kucoin.com/_api/currency/currency/chain-info) address for getting the chain id from network Name [chainName] and that gets me the chain id, did work.
