### ISSUE TITLE
The account type "isolated" is not supported, and an error is thrown if you have them 

### ISSUE THREAD

**Issue by pvanukoff** [JKorf/Kucoin.Net#159]
When I call GetAccountsAsync() on the SpotApi.Account endpoint, I get an error that says it can't convert "Type". Upon closer inspection, it's because I have two "isolated" margin accounts, and the "isolated" account type isn't present in the AccountType enum, nor supported in the AccountTypeConverter. I do have a fix for this locally and I'd be glad to submit a pull request for it. I just need to know which branch the PR should be against.

**Comment by JKorf** [comment]
I've added the Isolated margin account type in the latest version. For future reference, you can just PR into the master branch
