### ISSUE TITLE
GetSymbols for defined symbol returns no data

### ISSUE THREAD

**Issue by tkowalczyk** [JKorf/Kucoin.Net#16]
`_kucoinClient.GetSymbols("REQ-ETH");`
while
`_kucoinClient.GetSymbols();`
returns data with `REQ-ETH` symbol included

**Comment by tkowalczyk** [comment]
@JKorf any ideas here?

**Comment by JKorf** [comment]
Hi, sorry for the late reaction.

Seems the parameter was incorrectly named. It should be called 'market' and can be used to filter a specifc market; for example 'ALTS'. I've updated this in the latest version.
