### ISSUE TITLE
Method SpotApi.CommonSpotClient.GetSymbolsAsync(), wrong data, create order failed

### ISSUE THREAD

**Issue by masherak** [JKorf/Kucoin.Net#161]
Hello JKorf,

I can see a lot of fails during placing order because of -> "order_size_increment".

- I can see that priceDecimals and quantityDecimals are null, but this is minor problem here.
- On the second image you can see baseIncrement with 4 decimals, but in your library is QuantityStep with 5 decimals, do you use quoteIncrement here? I need to round amount asset for create order.

Thank you very much for your help

<img width="321" alt="image" src="https://user-images.githubusercontent.com/15813908/179599278-a0c96393-4d7f-4350-a31e-d033f35e489d.png">

<img width="288" alt="image" src="https://user-images.githubusercontent.com/15813908/179599484-cb073053-1ffc-434e-9541-e2a426be6bec.png">

**Comment by JKorf** [comment]
Thanks for the report, it was incorrectly mapped indeed. Fixed it in the latest version
