### ISSUE TITLE
Unable to start orderbook synchronization without default credentials

### ISSUE THREAD

**Issue by Matasx** [JKorf/Kucoin.Net#166]
**Describe the bug**
Call to Kucoin orderbook `StartAsync` fails with error `No API credentials provided for the default KucoinClient. Make sure API credentials are set using KucoinClient.SetDefaultOptions.` even when `RestClient` and `SocketClient` with prefilled credentials are provided within `KucoinOrderBookOptions`.

**To Reproduce**
```
var client = new KucoinClient(new KucoinClientOptions { ApiCredentials = credentials });
var socketClient = new KucoinSocketClient(new KucoinSocketClientOptions { ApiCredentials = credentials });

var ob = new KucoinOrderbook(symbol, new KucoinOrderBookOptions
            {
                RestClient = client,
                SocketClient = socketClient
            });
await ob.StartAsync(cancellationToken);
```

**Expected behavior**
Orderbook should connect and sychronize data.

Imagine a scenario where application wants to listen to 2 orderbooks, each from different Kucoin account or subaccount. There wouldn't be a clear way to support this just through setting global default credentials.

IMO `KucoinOrderBookOptions` should also support `ApiCredentials` override and it should respect setting `RestClient` and `SocketClient` with prefilled credentials.

**Debug logging**
```
Kucoin     | Kucoin order book HTR-USDT status changed: Disconnected => Connecting
Kucoin     | Kucoin order book HTR-USDT status changed: Connecting => Disconnected
```

**Comment by JKorf** [comment]
The requirement of having api credentials set has been removed by Kucoin. The next release will no longer need the credentials to be set
