### ISSUE TITLE
MarginMode.IsolatedMode does not work

### ISSUE THREAD

**Issue by mehranrezaei** [JKorf/Kucoin.Net#169]
Does this library support Isolated margin trading APIs?

I tried to place an order in isolated margin account:

```
var buyOrder = await _kucoinClient.SpotApi.Trading.PlaceMarginOrderAsync(
                                _symbol, OrderSide.Buy, NewOrderType.Market, 
                                quantity: normalizeQuantity, clientOrderId: _clientOrderIdPrefix,
                                marginMode: MarginMode.IsolatedMode);
```
But I get the following error:
```'Currently, the platform only supports the cross mode'```

What is the problem?

**Comment by JPizzal** [comment]
Has anyone ran into 429 error on Kucoin ?

Any wraps for it to get around this? 

They are optimizing the API in two weeks v1 v2 is no more and won't be for a while they said...

This crushed my bot.

Any help put there ladies and gents? Would be much obliged.

**Comment by JKorf** [comment]
The API only supports cross mode initially
