### ISSUE TITLE
SubscribeToAllTickerUpdatesAsync onData parameter without Inumerable

### ISSUE THREAD

**Issue by Maddest** [JKorf/Kucoin.Net#170]
Hi,
the first parameter of the function **SubscribeToAllTickerUpdatesAsync** is:
Action<DataEvent<KucoinStreamTick>> onData

Shouldn't it be?:
Action<DataEvent<IEnumerable<KucoinStreamTick>>> onData

I'm using this function on Binance and it gives me an array of Ticker data of all available symbols.

Here in the Kucoin version it gives me only the data of one symbol per event, because IEnumerable is not available.

Or do I miss something?

**Comment by JKorf** [comment]
Hi, you're not missing anything, but it's a difference in how the exchanges implemented the API. Subscribing to all ticker data on Binance will make the server push a list of all changed tickers per second. On Kucoin there is no aggegration, and every individual ticker is pushed as it changes.
Handling the Binance data is a bit easier, but there is not much I can do about that on the client side.

**Comment by Maddest** [comment]
Thanks a lot, Jan. Sad to hear that Kucoin is integrating his API that way.
So, I'll assume that the event load will be very heavy, about (max Kucoin Market Count / 2 seconds), which is about 750 events in 2 seconds max.

**Comment by JKorf** [comment]
Yup correct. You might want to do some aggregation on the client side, for example combining all events in a second before saving that data to a database to relieve some pressure on the database.

**Comment by Maddest** [comment]
Yeah, that was also my idea. Most intersting task to make it compatible to the Binance way of life. My app switches between exchanges and I need to offer the same functionality. 
Thanks again for your quick support :-)

**Comment by JPizzal** [comment]
Is anyone getting that renown 429 error? Is there a way around it in the futures api that anyone knows of?
