### ISSUE TITLE
Can not get Limit Order Untriggered Order

### ISSUE THREAD

**Issue by romidi** [JKorf/Kucoin.Net#171]
Hi, 

I have a Buy Limit order for SNX  which is not filled yet and attached as Image

Create a Limit order on Future

I tried following method 

**kclient.FuturesApi.Trading.GetOrdersAsync()** is not returning back SNXUSDT order
**kclient.FuturesApi.Trading.GetOrdersAsync().Result.Data** is not returning back SNXUSDT order
**kclient.FuturesApi.Trading.GetOrdersAsync().Result.Data.Items.Where(x => x.Symbol.Contains("snx"));** no result
**kclient.FuturesApi.Trading.GetUntriggeredStopOrdersAsync()** is returning empty

Which method should be used to get not filled order

![photo_2022-09-30_10-11-29](https://user-images.githubusercontent.com/36727639/193223877-38568788-08b9-42a6-9f3e-f006bacd0e2c.jpg)

**Comment by JKorf** [comment]
Have you been able to get this working? Also I'm not sure if you did this, but you might need to wait a couple of seconds before requesting the order after opening it, as the rest endpoint might not reflect changes immediately.

**Comment by romidi** [comment]
@JKorf I have updated to latest version 4.1.0 and i tested after one hour and still no result. can u try out your self.
example: put a buy order limit for btc at 10000 
Thanks

**Comment by JKorf** [comment]
Having a look at the API documentation it seems like you'd need to pass in the order status you want to retrieve. By default it will return only Done orders, if you want to request active order you'll have to call it like this:
`var result = await kucoinClient.FuturesApi.Trading.GetOrdersAsync(status: OrderStatus.Active);`

**Comment by romidi** [comment]
Thanks Jkorf. its working now.
