### ISSUE TITLE
Question - How to get information about WS status

### ISSUE THREAD

**Issue by masherak** [JKorf/Kucoin.Net#174]
Hello @JKorf,

After subscribe successful WS connection via method "SubscribeToOrderBookUpdatesAsync" I get "UpdateSubscription" as a response. How I can get "enum SocketStatus" from the namespace "CryptoExchange.Net.Sockets". I need to check if status == "Connected". Is there some other options how to check it? I cannot find public API to get this information.

Thank you very much!

**Comment by JKorf** [comment]
If the call to `SubscribeToOrderBookUpdatesAsync` retruns a UpdateSubscribe object in the Data property then the connection was successful. Normally you'd check for success results like this:
````csharp
var result = await client.CallAsync();
if (!result.Success)
{
  // Error
  var error = result.Error;
}
else
{
  // Success
  var result = result.Data;
}
````

**Comment by masherak** [comment]
Hello, thank you very much for your answer. I probably asked wrong. Lets look at the example. I have a running WS connection for two days, I have to internally store data from messages to have consistent state of order book. After that there can be something wrong and WS connection is unavailable, or problem with network on some side etc...How I can check that connection is still alive and properly connected to server? Because in case of not, I do not want to use my stored data. I can last message received timestamp, but there are pairs where is no changes for a few minutes...Thank you

**Comment by JKorf** [comment]
When you subscribe to using the socket client you can use the resulting object to subscribe to status updates. For example:
```csharp

var subResult  = await kucoinSocketClient.SpotStreams.SubscribeToXXX(DataHandler);
if(subResult.Success){
  subResult.Data.ConnectionLost += () => { /* Handle connection lost (socket will reconnect on it's own again) */ };
  subResult.Data.ConnectionRestored += (t) => { /* Handle connection restored */ };
}

```
