### ISSUE TITLE
SpotStreams.SubscribeToBalanceUpdatesAsync 400003: KC-API-KEY not exists

### ISSUE THREAD

**Issue by Papercut110** [JKorf/Kucoin.Net#175]
Hello, I'm trying to subscribe to spot balance updates on sandbox, but I encounter an error 400003: KC-API-KEY not exists. 
Rechecked key, secret and api key pass, there are no errors and it's definitely relate to spot account. What am I doing wrong?
![image](https://user-images.githubusercontent.com/58139424/198108235-2e8576ab-8f37-4a83-9e27-f8de4ca130af.png)

**Comment by Papercut110** [comment]
What am I doing wrong?

**Comment by JKorf** [comment]
Looks like you're using the testnet. Are the credentials you inserted also for the testnet?

**Comment by Papercut110** [comment]
> Looks like you're using the testnet. Are the credentials you inserted also for the testnet?
Yes, I double-checked several times. Rest requests with this Api Credentials work well.

**Comment by JKorf** [comment]
Since the socket connection url is determined by calling an endpoint via the rest client there are some difficulties in getting the 2 to line up when changing the base address. I think you can fix it by explicitely setting the default options for the rest client at the start like so:
```csharp
KucoinClient.SetDefaultOptions(new KucoinClientOptions
{
    SpotApiOptions = new KucoinRestApiClientOptions
    {
        BaseAddress = KucoinApiAddresses.TestNet.SpotAddress
    }
});
```

**Comment by Papercut110** [comment]
thanks a lot friend, it worked
