### ISSUE TITLE
PlaceStopOrderAsync Price increment invalid

### ISSUE THREAD

**Issue by Papercut110** [JKorf/Kucoin.Net#176]
Hello, please tell me what I'm doing wrong. I'm trying to set up an stoploss order on the spot in this way.

SpotApi.Trading.PlaceStopOrderAsync(symbol, OrderSide.Sell, NewOrderType.Limit, StopCondition.Loss, price, quantity: quantity, price: price);

But an error appears => Price increment invalid.
I specify the same price in the parameters stopPrice and price. I tried to set different prices in these two parameters, but the error is the same.

**Comment by JKorf** [comment]
I'm guessing your price has to many decimal places

**Comment by Papercut110** [comment]
> I'm guessing your price has to many decimal places

thanks a lot for the hint, you were right!
