### ISSUE TITLE
client.FuturesApi.ExchangeData.GetKlinesAsync - wrong data returned on 15min timeframe

### ISSUE THREAD

**Issue by WideAngleDev** [JKorf/Kucoin.Net#177]
When I try to get klines for AGLDUSDTM on 15min timeframe by using KuCoin Futures API, I get strange results. I get only 14 candles instead of approx 40, thus there are some missing candles. The OpenTime does not match 15 min difference.

Try this code to reproduce error:
string API_KEY = "<type api key here>";
            string API_SECRET = "<type secret key here>";
            string API_PASS_PHRASE = "<type pass phrase here>";
            KucoinClient client;
            Kucoin.Net.Objects.KucoinClientOptions options = new KucoinClientOptions();
            options.ApiCredentials = new KucoinApiCredentials(API_KEY, API_SECRET, API_PASS_PHRASE);
            KucoinClient.SetDefaultOptions(options);

            client = new KucoinClient();
            Task<WebCallResult<IEnumerable<KucoinFuturesKline>>> klinesTask = null;
            WebCallResult<IEnumerable<KucoinFuturesKline>> klines = null;
            DateTime startTime = new DateTime(2022, 11, 18, 7, 30, 00);
            DateTime endTime = new DateTime(2022, 11, 18, 19, 30, 00);
            klinesTask = client.FuturesApi.ExchangeData.GetKlinesAsync(symbol: "AGLDUSDTM", interval: FuturesKlineInterval.FifteenMinutes, startTime: startTime, endTime: endTime);
            klines = klinesTask.Result;
            foreach (KucoinFuturesKline k in klines.Data)
            {
                Console.WriteLine(k.OpenTime);
            }
The output is:
![image](https://user-images.githubusercontent.com/101290228/202803448-f9113bd8-6a67-4f8a-ae63-951bcc686523.png)

Expected behavior:
A proper amount of klines will be returned, each kline will have +15min in its OpenTime .

Version used:
I'm using KuCoin.NET v.4.2.0

**Comment by JKorf** [comment]
Can confirm, but it seems to be an issue with the Kucoin data. It might be that there is no data available for those missing klines, but I dont know. You might want to ask Kucoin support this.
