### ISSUE TITLE
GetDepositsAsync() not return result when passing status

### ISSUE THREAD

**Issue by H-Moradof** [JKorf/Kucoin.Net#180]
**Get Deposit List with Status filter**
When I call `GetDepositsAsync() `with `status: DepositStatus.Success`, nothing return (result.items is empty list), 
but if I don't send status parameter, it return many items with Success status !
So, as you can see, there is success deposits in that period of time (between `startTime `and `endTime`) and when I pass status to `GetDepositsAsync()` , it must return list of success deposits.

**To Reproduce**
My code is:

```
var coinSymbol = "USDT";
var depositDate = new DateTime(2022,12,4, 0,0,0);

var startTime = depositDate.ToUniversalTime();
var endTime = startTime.AddHours(1);            

var result = await _client.SpotApi.Account.GetDepositsAsync(
                asset: coinSymbol,
                startTime: startTime, 
                endTime: endTime,
                status: DepositStatus.Success, // this cause problem
                currentPage: 1,
                pageSize: 10);
```

if you look at KucoinClientSpotApiAccount class and GetDepositsAsync() method, you can see this line of code:

`parameters.AddOptionalParameter("status", status.HasValue ? JsonConvert.SerializeObject(status, new DepositStatusConverter(false)) : null);
`
I think something is wrong in this line of code.

**Expected behavior**
I expect when I pass DespositStatus.Success to GetDepositsAsync() method, return list of success deposits.

**Comment by JKorf** [comment]
Hello, I can't reproduce this. For me the parameters are working correctly to filter. Are you sure it isn't an issue iwth your timestamps?
