### ISSUE TITLE
How to create order with: Stop Loss and Take Profit?

### ISSUE THREAD

**Issue by mytran1998** [JKorf/Kucoin.Net#181]
Hey author and all, I have a issue need you confirm. 
I want create order with STOP LOSS & TAKE PROFIT price. But I don't find it in param setting.

Help me check it and fb solution, thanks you!!!

**Comment by JKorf** [comment]
Hi, have you had a look at https://jkorf.github.io/Kucoin.Net/Examples.html#placing-order ?

**Comment by mytran1998** [comment]
No,  I use FuturesAPI sir

**Comment by hildnerb** [comment]
Hi, i am also looking for the function. Have you found a solution?

**Comment by hildnerb** [comment]
i have found the solution. use: stopType: StopType.Down

`await _client.FuturesApi.Trading.PlaceOrderAsync(symbol + "M", OrderSide.Sell, typeEnum, leverage, quantity, stopPrice:6, stopPriceType:StopPriceType.TradePrice, closeOrder:true, stopType: StopType.Down);`
