### ISSUE TITLE
GetSymbolsAsync is missing 'minFunds' response parameter

### ISSUE THREAD

**Issue by Maddest** [JKorf/Kucoin.Net#182]
Hi JKorf,
I have realized that the function GetSymbolsAsync is missing the 'minFunds' response parameter.
Can you please add this parameter in the next update?
Thanks!!!

**Comment by dj-jordan** [comment]
Hiya, yes, Maddest is on the money...  

Knowing what the minimum investment for each symbol is most useful, be great to get 'minFunds' into the client
 (as would be getting accurate symbol base assets retuned by using v2 ion the api call /api/v2/symbols as per issue #184)

**Comment by JKorf** [comment]
Has been added in the latest version

**Comment by Maddest** [comment]
Thanks a lot :-) Already implemented and it works.
