### ISSUE TITLE
"GetDepositsAsync" and "GetWithdrawalsAsync" is missing 'chain' response parameter 

### ISSUE THREAD

**Issue by MohammadMehdiAhmadi** [JKorf/Kucoin.Net#183]
Hi JKorf,
I have realized that the function "GetDepositsAsync" and "GetWithdrawalsAsync" is missing the 'chain' response parameter.
Can you please add this parameter in the next update?
Thanks!!!

**Comment by JKorf** [comment]
Has been added in the latest version
