### ISSUE TITLE
please update GetSymbolsAsync() in to use v2 not v1 

### ISSUE THREAD

**Issue by dj-jordan** [JKorf/Kucoin.Net#184]
Hiya,

FYI..  Kucoin "/api/v1/symbols" is now depreciated, we need to now use v2
Refer notes at: [docs.kucoin.com/#get-symbols-list-deprecated](https://docs.kucoin.com/#get-symbols-list-deprecated)

- v2 is fully compatible with v1
- Two main differences exist between v1 and v2

1. The baseCurrency (baseAsset) is inaccurate in v1 as can be noted from the changes in the payload sample between [v1](https://docs.kucoin.com/#get-symbols-list-deprecated) and [v2](https://docs.kucoin.com/#get-symbols-list) - i.e. GALAX-USDT erroneously specifies the base asset as GALA (and not GALAX) in v1 
2. The API returns mixed case in v1 for some assets - e.g. aUSD  and ECOx in v1, which is AUSD and ECOX in v2.

- Can we please update the call to GetSymbolsAsync() so that it uses version 2 instead of 1...  
- From looking at the code, is the change as simple as adding 2 as the optional version parameter in the _baseClient.GetUri() call at approximately line 41 of KucoinClientSpotApiExchangeData.cs?

e.g.  `return await _baseClient.Execute<IEnumerable<KucoinSymbol>>(_baseClient.GetUri("symbols"**,2**), HttpMethod.Get, ct, parameters: parameters).ConfigureAwait(false);`

Thanks!
p.s.  While making edits to GetSymbolsAsync, can you please also add the missing 'minFunds' response paramter as per issue [#182](https://github.com/JKorf/Kucoin.Net/issues/182)

**Comment by dj-jordan** [comment]
Note in terms of case differences the full list of symbols with mixed case return issues in v1 are:
symbol |	name |	baseCurrency |	quoteCurrency |	minFunds
--+----+----+----+--	
LYXE-USDT |	LYXe-USDT |	LYXe |	USDT	0.1
LYXE-ETH |	LYXe-ETH |	LYXe |	ETH	0.00001
CUSD-USDT |	cUSD-USDT |	cUSD |	USDT	0.1
CUSD-BTC |	cUSD-BTC |	cUSD |	BTC	0.000001
AUSD-USDT |	AUSD-USDT |	aUSD |	USDT	0.1
ECOX-USDT |	ECOX-USDT |	ECOx |	USDT	0.1

**Comment by dj-jordan** [comment]
..and finally, for completeness, the full set of assets that have erroneous baseCurrency (baseAsset) data in v1 is

<img width="595" alt="image" src="https://user-images.githubusercontent.com/33166116/215557081-cde40790-dd78-46a7-b2f4-80d999398351.png">

Which are all nicely corrected in v2

**Comment by dj-jordan** [comment]
Note:  until GetSymbolsAsync() is updated to v2, I am using the following TSQL base to get correct base asset returns 

`SELECT	
 	CASE baseasset
		WHEN 'OXEN' THEN 'LOKI'
		WHEN 'REV'	THEN 'REVV'
		WHEN 'BSV'	THEN 'BCHSV'
		WHEN 'WAXP' THEN 'WAX'
		WHEN 'GALA' THEN 'GALAX'
		ELSE upper(baseasset)
	END as baseasset
	
FROM kucoin_symbol_info_table`

**Comment by JKorf** [comment]
I've switched it to V2 and added the minFunds property in the latest version. Thanks for the detailed report
