### ISSUE TITLE
WithdrawAsync() feeDeductType not supported!

### ISSUE THREAD

**Issue by samanbahrekazemi** [JKorf/Kucoin.Net#185]
await client.SpotApi.Account.WithdrawAsync();

https://docs.kucoin.com/#apply-withdraw-2

Withdrawal fee deduction type: INTERNAL or EXTERNAL

fee deucted from account but I want deduct the transaction fees from withdrawal account.

**Comment by JKorf** [comment]
Has been added in the latest version

**Comment by samanbahrekazemi** [comment]
Thanks a lot.
