### ISSUE TITLE
Get Balances Linq select SourceObject Type

### ISSUE THREAD

**Issue by NinjaRaiden** [JKorf/Kucoin.Net#186]
Hello, I can not use linq to filter and select balances where SourceObject.Type = Trade or Main.
```
var x = kucoinClient.SpotApi.CommonSpotClient.GetBalancesAsync().Result;
            x.Data.Where(m => m.SourceObject.Type == ?)
```

**Comment by Torabi-srh** [comment]
check the SourceObject Type its {Kucoin.Net.Objects.Models.Spot.KucoinAccount} in Spot API i think you doing it wrong.

**Comment by NinjaRaiden** [comment]
> check the SourceObject Type its {Kucoin.Net.Objects.Models.Spot.KucoinAccount} in Spot API i think you doing it wrong.

Yes you can check the SourceObject Type with Casting. 
but you can't filter **Where** condition with SourceObject  cause it need to casting first.

in order to achieve that:
```
KucoinAccount l =  (KucoinAccount) b.SourceObject;
switch (l.Type)
{
    case AccountType.Trade:{}break;
    .
    .
    .
}
```

**Comment by JKorf** [comment]
Closing due to cleaning up old issues
The CommonSpotClient has been deprecated in favor of the SharedClient implementation, which should be better usable
