### ISSUE TITLE
Add chain to Kucoin.Net.Objects.Models.Spot.KucoinAssetNetwork

### ISSUE THREAD

**Issue by NinjaRaiden** [JKorf/Kucoin.Net#187]
in kucoinClient.SpotApi.ExchangeData.GetAssetAsync function we have access to **NetworkName** which I assume is "chainName" from json response, but no to "chain".

{"chainName":"BEP20","chain":"bsc","withdrawalMinSize":"10","withdrawalMinFee":"5","isWithdrawEnabled":false,"isDepositEnabled":false,"confirms":32,"contractAddress":""}

Please add another property name "Chain".
Its useful for Withdraw or CreateDepositeAddress that need chain.

**Comment by shayangha** [comment]
I need too

**Comment by JKorf** [comment]
Has been added
