### ISSUE TITLE
futures post order qty, kucoin don't accept decimals

### ISSUE THREAD

**Issue by uranio-235** [JKorf/Kucoin.Net#188]
**Describe the bug**
Qty is being sent as decimal at IKucoinClientFuturesApiTrading.PlaceOrderAsync (implementation)

Response from kucoin after sent 1 as qty:

```json
{
  "code": "100000",
  "msg": "JSON parse error: Cannot deserialize value of type `java.lang.Long` from String \"1.0\": not a valid `java.lang.Long` value; "
}
```

**Comment by uranio-235** [comment]
https://github.com/JKorf/Kucoin.Net/pull/189

**Comment by jacksoliman** [comment]
You're sending "1.0" not "1".
You need to send an integer not a decimal, float, or in your case "long". You're buying or selling lots not coins. And you can't buy or sell half a lot. You need to round it and make sure the data type is integer.

**Comment by JKorf** [comment]
Changed it to int
