### ISSUE TITLE
order.DealQuantity question

### ISSUE THREAD

**Issue by thraxxus** [JKorf/Kucoin.Net#19]
My understanding of this value order.DealQuantity is that it told you how much of amount was executed.

Meaning if I tried to sell 1 btc, and it sold .5 btc, then order.DealQuantity would hold .5

Is that wrong?

I asked because I use this value to see if my order was completely filled or not and have noticed that lately it is saying the order.DealQuantity is the same as the amount I submitted to use, which would imply the order is complete - but when I look at the exchange, the order is not complete and does not have that same amount.

**Comment by JKorf** [comment]
Seems to me like you are correct. The library maps dealSize to the DealQuantity property, and the dealSize is descripted as follows in the Kucoin API docs:
dealSize | executed quantity

I'm not sure why this data would be incorrect vs the web exchange.

**Comment by thraxxus** [comment]
Also the IsActive flag is causing issues. 

I use IsActive first to see if the order is still in play.

Then I use the DealQuantity to see what happened.

Recently they both went wonky - not at all trustable.

**Comment by thraxxus** [comment]
How would you suggest we look to see if an order is complete or not otherwise?

**Comment by JKorf** [comment]
You should probably ask the Kucoin team this
