### ISSUE TITLE
Placing Order using WebSocket

### ISSUE THREAD

**Issue by MSLight** [JKorf/Kucoin.Net#192]
Is there any way to Placing an order using Futures or Spot WebSocket?

Using Client for this causes delay and I can't place my order at the time I want.

Based on some Information on the API documentation and my research on the web it's possible to Place an order using WebSocket. But I don't have enough skills to Implement them.

Please add this feature in next update.
Thanks a lot.

**Comment by jacksoliman** [comment]
No. You can't place orders through WebSocket. It doesn't say anything like this in the documentation.
WebSocket is for streaming data only. Order updates, price changes ... etc.
