### ISSUE TITLE
Futures Websocket connection error.

### ISSUE THREAD

**Issue by jacksoliman** [JKorf/Kucoin.Net#193]
Hope everyone is having a good day.

I subscribe to either SubscribeToMarketUpdatesAsync() to get Mark price updates or SubscribeTo24HourSnapshotUpdatesAsync() to get trade price updates. I have option to select one or another.

If the subscription is successful, I activate events to raise an alarm if the call result <UpdateSubscription> returns:
connection lost, connection restored, or connection closed.

This was working perfect with no issues until recently. 
The connection now keeps disconnecting and reconnecting once every 1-3 minutes.
I attached a picture of the events handling the connection alarm.

Your time helping me figuring this out is appreciated.

![websocket_1](https://user-images.githubusercontent.com/86846715/230725025-497e8eb1-3c12-4006-b025-5f66fa7e694f.jpg)

**Comment by vgpro54321** [comment]
I am suspecting the underlying cause is this: https://github.com/JKorf/Kucoin.Net/issues/195

**Comment by JKorf** [comment]
Has been fixed in the latest version
