### ISSUE TITLE
Futures socket connection does not ping

### ISSUE THREAD

**Issue by vgpro54321** [JKorf/Kucoin.Net#195]
Hello Guys,

I am noticing that futures socket is disconnecting at 1 minute intervals, disconnect look like initiated by server. I see that Kucoin documentation requires 60 seconds pings but pings are only issued by spot socket client, not by futures client.

I noticed that there is a difference in KucoinSocketClientSpotStreams and KucoinSocketClientFuturesStreams constructors: futures class does not hook up pinging infrastructure.

```

 internal KucoinSocketClientSpotStreams(Log log, KucoinSocketClient baseClient, KucoinSocketClientOptions options)
            : base(log, options, options.SpotStreamsOptions)
        {
            _baseClient = baseClient;
            _options = options;

            **SendPeriodic("Ping", TimeSpan.FromSeconds(30), (connection) => new KucoinPing()
            {
                Id = Math.Round((DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalMilliseconds).ToString(CultureInfo.InvariantCulture),
                Type = "ping"
            });

            AddGenericHandler("Ping", (messageEvent) => { });
            AddGenericHandler("Welcome", (messageEvent) => { });**
        }


```

**Comment by JKorf** [comment]
Has been fixed in the latest version
