### ISSUE TITLE
All requests going to V1

### ISSUE THREAD

**Issue by andresdrb** [JKorf/Kucoin.Net#198]
How do you actually set the clients to use the Kucoin V2 api? I get errors all the time because all the requests go to the V1 and I don't see any evident property where to set the version to use

![image](https://user-images.githubusercontent.com/9131538/236353734-31037011-9af6-43da-a6a4-bbe773bbce9b.png)

**Comment by andresdrb** [comment]
I figured out something. If you DON'T set the base address  on the client options it works as expected, but if you set the base address on the options (https://api.kucoin.com) it routes all requests to V1 (the librery adds v1 to the base address). This is very counter-intuitive

**Comment by JKorf** [comment]
The normal API address is `https://api.kucoin.com/api/`, so I'm guessing the issue comes from not having the `/api/` on the end

**Comment by andresdrb** [comment]
the API documentation states the base URL as without the /api, hence why I think it is counter intuitive…

![image](https://user-images.githubusercontent.com/9131538/236619776-11613a1a-1238-4bc0-a1cb-4c343642ef31.jpg)

**Comment by JKorf** [comment]
I see. In the next bigger update I'll be updating the BaseAdress/Environment, I'll look into addressing this

**Comment by JKorf** [comment]
With the latest release this should be more user friendly and intuitive. Let me know if you have any other issues
