### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by IvanResh** [JKorf/Kucoin.Net#2]
Hello!

I noticed you missed to send parameters to Execute<> method at the 964 line:
`var parameters = new Dictionary<string, object>();
            parameters.AddOptionalParameter("symbol", symbol);
            parameters.AddOptionalParameter("side", side.HasValue ? JsonConvert.SerializeObject(side, new OrderSideConverter(false)) : null);
            parameters.AddOptionalParameter("startAt", startTime.HasValue ? JsonConvert.SerializeObject(startTime, new TimestampSecondsConverter()) : null);
            parameters.AddOptionalParameter("endAt", startTime.HasValue ? JsonConvert.SerializeObject(endTime, new TimestampSecondsConverter()) : null);
            parameters.AddOptionalParameter("currentPage", currentPage);
            parameters.AddOptionalParameter("pageSize", pageSize);

            return await Execute<KucoinPaginated<KucoinHistoricalOrder>>(GetUri($"hist-orders"), signed: true).ConfigureAwait(false);
        }`

**Comment by JKorf** [comment]
Hi, thanks for the report. I've fixed it and a new version should be available in a few minutes.
