### ISSUE TITLE
Error deserializing data

### ISSUE THREAD

**Issue by IsseDisse** [JKorf/Kucoin.Net#20]
Hi,
since few days when I call _kucoinClient.GetOrdersAsync i get the following JsonSerializationException. For the most of the requested orders the price is null and the json serializer doesn't seem to ignore the zero value. I've 20 items in the list and only the first has '0' as value. JFYI: I removed some properties from the json.

2020.11.17 09:04:11:565 | Error | [6] Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'data.items[1].price', line 1, position 801.. Received data: {
  "code": "200000",
  "data": {
    "currentPage": 1,
    "pageSize": 50,
    "totalNum": 20,
    "totalPage": 1,
    "items": [
      {
        "symbol": "LTC-BTC",
        "opType": "DEAL",
        "type": "market",
        "side": "sell",
        "price": "0",
        "feeCurrency": "BTC",
        "stp": "",
        "stop": "loss",
        "stopTriggered": true,
        "timeInForce": "GTT",
        "postOnly": false,
        "hidden": false,
        "iceberg": false,
        "visibleSize": "0",
        "cancelAfter": 0,
        "channel": "API",
        "tags": null,
        "isActive": false,
        "cancelExist": false,
        "createdAt": 1605435010000,
        "tradeType": "TRADE"
      },
      {
        "symbol": "LTC-BTC",
        "opType": "DEAL",
        "type": "market",
        "side": "sell",
        "price": null,
        "funds": null,
        "dealFunds": null,
        "dealSize": "0",
        "fee": "0",
        "feeCurrency": "BTC",
        "stp": null,
        "stop": "loss",
        "stopTriggered": true,
        "timeInForce": "GTT",
        "postOnly": false,
        "hidden": false,
        "iceberg": false,
        "visibleSize": null,
        "cancelAfter": 0,
        "channel": "API",
        "tags": null,
        "isActive": false,
        "cancelExist": true,
        "createdAt": 1605419956479,
        "tradeType": "TRADE"
      },

Best regards

**Comment by JKorf** [comment]
This should be fixed in the latest version
