### ISSUE TITLE
add new status deposit

### ISSUE THREAD

**Issue by coderxlsn** [JKorf/Kucoin.Net#210]
in your personal account in the method
https://www.kucoin.com/_api/payment/deposit/list?page=1&currentPage=1&pageSize=10&currency=&version=2&
there is a status
PRE_SUCCESS
the status is returned to the API 
SUCCESS

**Comment by JKorf** [comment]
I'm not sure what you mean, that API is not part of library. The API for public usage is this one:
https://www.kucoin.com/docs/rest/funding/deposit/get-deposit-list?x=nl_NL
which seems to be implemented correctly.
