### ISSUE TITLE
Missing fields in Updated SpotApi.ExchangeData.GetAssetsAsync to V3 API

### ISSUE THREAD

**Issue by PhilAlain** [JKorf/Kucoin.Net#213]
Hello Jan,
Thanks again for your great work !

Two fields are missing in the class KucoinAssetNetwork, to match:
depositFeeRate
depositMinSize

To reproduce, check the URL below for USDT under chainName BEP20 for instance:
https://[api.kucoin.com/api/v3/currencies/USDT](https://api.kucoin.com/api/v3/currencies/USDT)

Actually this is true for 3 of the USDT blockchains.

Best Regards,
Phil

**Comment by JKorf** [comment]
Thanks for the PR, included in latest release
