### ISSUE TITLE
Orderbook encountered error after upgrading to version 5.2

### ISSUE THREAD

**Issue by sc-starman** [JKorf/Kucoin.Net#217]
**Describe the bug**
upgrading from 5.1 to 5.2, orderbook subscribing encounters error.
from logs:
[Sckt 1] failed to subscribe: [ServerError] Connection interupted
Sckt 1] failed reconnect processing: [CancellationRequestedError] Query timeout , reconnecting again

rollback to 5.1 and everything back to normal

**Comment by JKorf** [comment]
I checked it just now, seems to be working correctly for me with the latest version. But the logging seems to indicate that its failing to reconnect instead of failing to initially connect, is that right?
