### ISSUE TITLE
Missing BalanceUpdates from ProAccount on SpotApi SocketClient 

### ISSUE THREAD

**Issue by bogdanyel** [JKorf/Kucoin.Net#220]
**Describe the bug**
The `SpotApi` `KucoinSocketClient` `SubscribeToBalanceUpdatesAsync` doesn't receive any balance updates from the `HighFrequencyTrading` account. Balance updates from the normal `TradingAccount` arrive as expected.
This issues seems to come with the latest updates (I was sitting a few versions back).

**To Reproduce**
Subscribe to balance updates via the `KucoinSocketClient` `SpotApi.SubscribeToBalanceUpdatesAsync`, trigger a wallet update inside the `ProAccount` / `HighFrequencyTrading` (like place a limit order), and notice the missing balance updates.

**Expected behavior**
Wallet updates from both `TradingAccount` and `HighFrequencyAccount` should be received!

**Comment by JKorf** [comment]
Thanks for the report, has been fixed in the latest version
