### ISSUE TITLE
UpdateTime and EndTime missing in FuturesAPI

### ISSUE THREAD

**Issue by SRNebu2007** [JKorf/Kucoin.Net#227]
**Describe the bug**
var resultClosedOrders = await kucoinClient.FuturesApi.CommonFuturesClient.GetClosedOrdersAsync(xxx);
In the result retunred from server we have date information about the open and the close time (even updatetime). But there is no field that includes this information. Currently I have to apre it from the data object. I would like to have those DateTime fields added and filled directly.
<img width="428" alt="image" src="https://github.com/user-attachments/assets/530d4aad-f14c-44aa-bffe-ac2d93cad6fa">

**To Reproduce**
Just use the call and see in the datasoruce

**Expected behavior**
2 additional fields.
Those fields will help to find a link of an order and a created position

Thanks for your hard work.

**Comment by JKorf** [comment]
Hi, just to check, you are aware that you're using the `Common` interface? It's a set of common functionality available on different exchanges, which means that the models don't have all data available from the API specific calls.

If you're looking for the full API, use `kucoinClient.FuturesApi.Trading.GetClosedOdersAsync`.
If you're intentionally using the common interface; I'm not fond of the current implementation and plan on reworking it. So for short term I probably won't change this.
