### ISSUE TITLE
Error while placing borrow order.

### ISSUE THREAD

**Issue by alokym86** [JKorf/Kucoin.Net#230]
Looks like the method `SpotApi.Margin.BorrowAsync()` should request with  `IOC` or  `FOK` as `timeInForce` parameter, not `ImmediateOrCancel` or `FillOrKill`.  Here API endpoint doc https://www.kucoin.com/docs/rest/margin-trading/margin-trading-v3-/margin-borrowing.

**To Reproduce**
```
var restClient = new KucoinRestClient(options =>
        {
            options.ApiCredentials =
                new KucoinApiCredentials("key", "secret", "passphrase");
        })
var response = await restClient.SpotApi.Margin.BorrowAsync(
            asset: "LINK",
            quantity: 2.0m
            timeInForce: TimeInForce.FillOrKill
        );
 ```

**Debug logging**
```
Sending POST api/v3/margin/borrow authenticated request with body {"currency":"LINK","size":2.0,"timeInForce":"FillOrKill"}
...
200 - Response received in 357ms: {"msg":"unknown timeInForce","code":"400100"}
```

**Comment by JKorf** [comment]
Has been fixed in the latest version

**Comment by JKorf** [comment]
Sorry, seems like this wasn't in the release yet

**Comment by JKorf** [comment]
It's been fixed in last release now
