### ISSUE TITLE
Method GetBalancesAsync under interface IBalanceRestClient not working

### ISSUE THREAD

**Issue by masherak** [JKorf/Kucoin.Net#236]
Good afternoon, 

the method GetBalancesAsync(IBalanceRestClient) returns an empty list with no balances. I have tried different TradingMode values, but KuCoin only supports “Spot”. I also attempted leaving the GetBalancesRequest parameter as null, but none of these approaches worked. In all cases, I am unable to retrieve any balances.

![image](https://github.com/user-attachments/assets/30493e08-16cd-47f5-99d7-6a96569b53c6)

The only way I am able to retrieve balances is by using the method GetAccountsAsync under SpotApi.Account (as shown in the image). This method works, but it does not belong to the shared APIs.

![image](https://github.com/user-attachments/assets/b0783d4d-fdbb-4da1-8e3f-2fef7955fce2)

On KuCoin, there are different types of accounts, and I am primarily interested in the “Trading” account. I assumed this would correspond to the “Spot” type in the shared APIs. 

Am I misunderstanding this, or is this a bug?

Thank you for your response.

**Comment by JKorf** [comment]
Hi, by default the Shared interface implementation will try to return all `trade_hf` type balances. These are the `HighFrequency` trade account balances. The HighFrequency account is what Kucoin is switching over to. If you're still working with the older account type you can set the `HfTrading` parameter to false.

For all endpoints which have different versions for HF:
```csharp
kucoinRestClient.SpotApi.SharedClient.SetDefaultExchangeParameter("HfTrading", false);
var result = await kucoinRestClient.SpotApi.SharedClient.GetBalancesAsync(new GetBalancesRequest());
```
or for just this specific call:
```csharp
var exchangeParameters = new ExchangeParameters(new ExchangeParameter("Kucoin", "HfTrading", false));
var result = await kucoinRestClient.SpotApi.SharedClient.GetBalancesAsync(new GetBalancesRequest(exchangeParameters: exchangeParameters));
```

**Comment by masherak** [comment]
@JKorf Hello, I apologize for the delayed response. I was dealing with this issue with Kucoin support, and it took some time. Apparently, using the trade_hf account (or other HF accounts) is no longer supported. I don’t have this account and never will. The HF endpoints can now be called from a standard trade account, and this is the final state for accounts that have already been migrated. According to what I found out, the migration took place in February 2024. Now, I’m not sure what to do about this. Are you planning to update the SDK considering these changes? Or should I handle it on my end with custom parameters? Thank you for your help.

<img width="481" alt="image" src="https://github.com/user-attachments/assets/0a526cfe-92e6-458e-9f5f-1f14d76b8307" />

**Comment by masherak** [comment]
@JKorf Friendly reminder

**Comment by JKorf** [comment]
Hi, I've updated the logic in the latest version to only try and filter the results if both SpotHf and Trade balance types are returned (which is in my case). If only SpotHf or only Trade balance types are returned then that will be returned to the user.
