### ISSUE TITLE
Caching PASSPHRASE problem

### ISSUE THREAD

**Issue by usuf13** [JKorf/Kucoin.Net#238]
**Describe the bug**
passphrase caching works badly and does not cover cases of using the same passphrase for different keys
https://github.com/JKorf/Kucoin.Net/blob/063ec589eb8db3e99eebf79fdf3f30eba5c9c628/Kucoin.Net/KucoinAuthenticationProvider.cs#L60

**To Reproduce**
- Create 2 API keys with the same passphrase
- Create 2 instances of KucoinRestClient and SetApiCredentials
- Get balance for each by SpotApi.Account.GetAccountsAsync

Only the first return balance, the second instance returns Invalid KC-API-PASSPHRASE

**Expected behavior**
passphrase cache key must include an API key for using the correct value

**Comment by JKorf** [comment]
You're totally right. I've fixed it in the latest version.
