### ISSUE TITLE
404 on current version

### ISSUE THREAD

**Issue by spitefulgod** [JKorf/Kucoin.Net#25]
KucoinClient.SetDefaultOptions(new KucoinClientOptions()
{
    ApiCredentials = new KucoinApiCredentials(KucoinAPIKey, KucoinAPISecret, Phrase),
    LogVerbosity = LogVerbosity.Warning | LogVerbosity.Error,
    LogWriters = new List<TextWriter> { Console.Out }
});

using (KucoinClient Conn = new KucoinClient())
{
    WebCallResult<KucoinFullOrderBook> OB = Conn.GetOrderBook(Data.Base + "-" + Data.Quote);
}

Success Return 0 with the error 404: Not Exists

**Comment by JKorf** [comment]
Hi, I've just pushed a new version 2.3.3 in which this should be fixed.

**Comment by spitefulgod** [comment]
Thank you JKorf, I'll re-embers you in the future a portion of any profits I make for your hard work.
