### ISSUE TITLE
GetOrderBook Returns non de-serializable data

### ISSUE THREAD

**Issue by spitefulgod** [JKorf/Kucoin.Net#26]
A call to GetOrderBook fails with the error
"Deserialize Unknown Exception: Value to add was out of range. (Parameter 'value')\r\n"

Here is some sample JSON return from the API, I believe the fault probably lies in the 4th parameter with it being a large number.

["5ffb608de64d620006d5bad4","1","0.01",1610309773736425216],["60038002833e6b00068b7254","1","0.7",1610842114614649119],["5f3b3012e69b040007d2317d","2","4.1041",1597714450332568748],["604bf3544ea78a00066d11c0","25","17.7619",1615590229017504805],["602c289af37bfc00069b95ca","48","12.966",1613506714307652894]

**Comment by JKorf** [comment]
Ah I should have seen that, I've fixed the deserialization in 2.3.4

**Comment by spitefulgod** [comment]
Working, Thanks.
