### ISSUE TITLE
GetKlines

### ISSUE THREAD

**Issue by thraxxus** [JKorf/Kucoin.Net#29]
I just did a rather large test for GetKlines.
For BTC-USDT I pulled 159000 minutes of data from Kucoin.

I noticed some grossness.

If you do that you will find a pattern of 105 of each result responded - meaning kucoin returns the same data on a cycle - also, the data is actually wrong.

Have you noticed this?

**Comment by JKorf** [comment]
I haven't, but I also haven't been using Kucoin extensively. Can you elaborate a bit more on the the calls you did and what you'd expect?

**Comment by thraxxus** [comment]
WebCallResult<IEnumerable<KucoinKline>> kks = GetPairData(pair, timePeriod);

Do this for a few thousand minutes of time period, store in a db, then sort the data. You will see a repeatable pattern emerge. 
In mine it was the same data 105 minute intervals.
