### ISSUE TITLE
Serialization of GetOrders response fails if SelfTradePrevention param is empty for some orders

### ISSUE THREAD

**Issue by o2shik** [JKorf/Kucoin.Net#3]
If an order is sent without setting SelfTradePrevention param GetOrders response fails on deserialization of stp field. Below is a fix.

 Kucoin.Net/Converts/SelfTradePreventionConverter.cs | 1 +
 Kucoin.Net/Objects/KucoinEnums.cs                   | 4 ++++
 2 files changed, 5 insertions(+)

diff --git a/Kucoin.Net/Converts/SelfTradePreventionConverter.cs b/Kucoin.Net/Converts/SelfTradePreventionConverter.cs
index 1c05842..3220bf5 100644
--- a/Kucoin.Net/Converts/SelfTradePreventionConverter.cs
+++ b/Kucoin.Net/Converts/SelfTradePreventionConverter.cs
@@ -10,6 +10,7 @@ namespace Kucoin.Net.Converts
         public SelfTradePreventionConverter(bool quotes) : base(quotes) { }
         protected override List<KeyValuePair<KucoinSelfTradePrevention, string>> Mapping => new List<KeyValuePair<KucoinSelfTradePrevention, string>>
         {
+            new KeyValuePair<KucoinSelfTradePrevention, string>(KucoinSelfTradePrevention.None, ""),
             new KeyValuePair<KucoinSelfTradePrevention, string>(KucoinSelfTradePrevention.DecreaseAndCancel, "DC"),
             new KeyValuePair<KucoinSelfTradePrevention, string>(KucoinSelfTradePrevention.CancelOldest, "CO"),
             new KeyValuePair<KucoinSelfTradePrevention, string>(KucoinSelfTradePrevention.CancelNewest, "CN"),
diff --git a/Kucoin.Net/Objects/KucoinEnums.cs b/Kucoin.Net/Objects/KucoinEnums.cs
index b38833b..187f905 100644
--- a/Kucoin.Net/Objects/KucoinEnums.cs
+++ b/Kucoin.Net/Objects/KucoinEnums.cs
@@ -197,6 +197,10 @@
     /// </summary>
     public enum KucoinSelfTradePrevention
     {
+        /// <summary>
+        /// Self Trade Prevention Disabled
+        /// </summary>
+        None,
         /// <summary>
         /// Decrease the amount of the existing order by the amount of the new order
         /// </summary>

**Comment by JKorf** [comment]
Hi, thanks for the report. I've pushed a fix for it, version 1.0.4 should be available in a few minutes.
