### ISSUE TITLE
PlaceOrder returns "Insufficient Balance"

### ISSUE THREAD

**Issue by futuristly** [JKorf/Kucoin.Net#31]
I have a problem with bellow code:

`var buyOrderResult = _kucoinClient.PlaceOrder(
                    solbot.Strategy.AvailableStrategy.Symbol,
                    Kucoin.Net.Objects.KucoinOrderSide.Buy,
                    Kucoin.Net.Objects.KucoinNewOrderType.Market,
                    funds: solbot.Communication.Buy.AvailableFund);`

every time I tried to place an order on exchange I am getting error `200004`  Balance insufficient!

![image](https://user-images.githubusercontent.com/79585066/113750532-d8535200-9702-11eb-9721-db0981adfe6e.png)

What is wrong? I have enough balance, I am also able to trade manually via web interface etc.
Any help?

**Comment by JKorf** [comment]
Make sure the funds are in the correct wallet

**Comment by Borkanie** [comment]
i have funds in wallet but how can i choose which wallet the order uses?

**Comment by Robot-Stack** [comment]
Yeah thats a Kucoin problem the funds won't get accounted, but SubscribeToOrderUpdates socket event already shows data. i have solved it with a simple retry executing orders 4 times 500ms timespan... always works around after the 2nd try.
