### ISSUE TITLE
Deserialization fails for KuCoinOrders with a null 'size' field

### ISSUE THREAD

**Issue by OasisOfChaos** [JKorf/Kucoin.Net#37]
**Describe the bug**
When retrieving the orders with GetOrdersAsync() the deserialization fails when the decimal field '`Quantity`' (with the `[JsonProperty("size")]`) contains a null value.

**To Reproduce**
I have manually created a stop-loss order and then canceled that order again via the Kucoin web interface. When I then try to get the order with GetOrdersAsync() the call fails:
`Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'data.items[3].size', line 1, position 1822.`

When I modify the Kucoin.Net code so that decimal field becomes nullable, I can retrieve the data sucessfully. Proof of this situation:

`    {
      "Id": "vs8sgo4his8l5pje0037mjei",
      "Symbol": "BTC-USDT",
      "opType": "DEAL",
      "Type": "market",
      "Side": "buy",
      "Price": null,
      "size": null,
      "Funds": 1.0,
      "DealFunds": null,
      "dealSize": 0.0,
      "Fee": 0.0,
      "FeeCurrency": "USDT",
      "stp": null,
      "Stop": "loss",
      "StopTriggered": false,
      "StopPrice": 54400.0,
      "TimeInForce": "GTC",
      "PostOnly": false,
      "Hidden": false,
      "Iceberg": false,
      "visibleSize": null,
      "CancelAfter": -1,
      "Channel": "WEB",
      "clientOid": null,
      "Remark": null,
      "Tags": null,
      "IsActive": false,
      "CancelExist": true,
      "CreatedAt": 1620154129416
    },
 `

**Comment by JKorf** [comment]
Thanks for the details, in version 2.3.9 this is fixed.

**Comment by OasisOfChaos** [comment]
Thank you for your quick solution. It's working perfectly now.
