### ISSUE TITLE
Socket Channels do not respect a custom BaseUrl

### ISSUE THREAD

**Issue by OasisOfChaos** [JKorf/Kucoin.Net#38]
**Describe the bug**
When specifying a non-default BaseUrl for the KucoinSocketClientOptions like so

```
            var options = new KucoinSocketClientOptions()
            {
                BaseAddress = "https://openapi-sandbox.kucoin.com/api"
            };

```
the `SocketClient()` still uses the `BaseUrl` specified in the DefaultOptions of the `KucoinClient` (it copies it).

**To Reproduce**
```

            var options = new KucoinSocketClientOptions()
            {
                BaseAddress = "https://openapi-sandbox.kucoin.com/api"
            };

            var ou = sclient.SubscribeToOrderUpdates(onOrderData =>
            {
                Console.WriteLine($"SubscribeToOrderUpdates/onOrderData: order update for ClientOrderid {onOrderData.ClientOrderid}");
            }, onTradeData =>
            {
                Console.WriteLine($"SubscribeToOrderUpdates/onTradeData: order update for ClientOrderid {onTradeData.ClientOrderid}");
            });
```

`ou` contains an Error situation with the message 'KC-API-KEY not exists'. That fits, because that api key does not exist in the default Kucoin environment.

If one replaces the default BaseUrl with the one passed in the Subscribe method in the KucoinSocketClient class, it works as expected:
```
KucoinToken token;
var clientOptions = KucoinClient.DefaultOptions.Copy();

clientOptions.BaseAddress = url;   // this helps

KucoinApiCredentials? thisCredentials = (KucoinApiCredentials?)authProvider?.Credentials;
```

Also, the method 'SubscribeToStopOrderUpdatesAsync()' is not marked as 'private' so the subscription fails.

```return await Subscribe(request, null, false, innerHandler).ConfigureAwait(false);```

should be

```return await Subscribe(request, null, true, innerHandler).ConfigureAwait(false);```

(sorry, not really familiar with contributing yet, next time i'll try to fix this in a PR..)

**Comment by JKorf** [comment]
I've fixed the SubscribeToStopOrderUpdatesAsync not being authenticated, thanks for the heads up. It will be fixed in the next release.

Regarding the base address, you can't set the BaseAddress of the KucoinClientOptions, which are for the KucoinClient, to the same address as the KucoinSocketClientOptions, which are for the KucoinSocketClient. They might be 2 completely different url's. You can fix this by setting the default options of the KucoinClient (not the KucoinSocketClient) with the url you need.
Something like 
````C#
KucoinClient.SetDefaultOptions(new KucoinClientOptions {
    BaseAddress = "xxx"
});
````
