### ISSUE TITLE
Mixed up BestBid and BestAsk in KucoinAllTick

### ISSUE THREAD

**Issue by o2shik** [JKorf/Kucoin.Net#4]
`diff` --git a/Kucoin.Net/Objects/KucoinAllTick.cs b/Kucoin.Net/Objects/KucoinAllTick.cs
`index ed13c55..395339e 100644
`--- a/Kucoin.Net/Objects/KucoinAllTick.cs
`+++ b/Kucoin.Net/Objects/KucoinAllTick.cs
`@@ -15,12 +15,12 @@ namespace Kucoin.Net.Objects
`         /// The best ask price
`         /// </summary>
`         [JsonProperty("buy")]
`-        public decimal BestAsk { get; set; }
`+        public decimal BestBid { get; set; }
`         /// <summary>
`         /// The best bid price
`         /// </summary>
`         [JsonProperty("sell")]
`-        public decimal BestBid { get; set; }
`+        public decimal BestAsk { get; set; }
`         /// <summary>
`         /// The prentage change
`         /// </summary>

**Comment by JKorf** [comment]
Hi, thanks for the report. I've pushed a fix for it, version 1.0.4 should be available in a few minutes.
