### ISSUE TITLE
Is there a volume property in the ticker subscription?

### ISSUE THREAD

**Issue by ertan2002** [JKorf/Kucoin.Net#43]
I see that there is no a volume property in the KucoinStreamTick class by using SubscribeToTickerUpdates.

I would like to observe a coin's volume changes by using subscribtion method (if there is another way, please share it with me)

In the kucoin API documentation, there is a volume property
https://docs.kucoin.com/#get-all-tickers

but the onData delegate from the SubscribeToTickerUpdates does not give the volume.

I can see the volume by calling Get24HourStats method but I do not want to call constantly this method and prefer to do this task with a listener.

**Comment by JKorf** [comment]
The SubscribeToTickerUpdates is a websocket subscription, and the link you reference is a rest API endpoint. Rest endpoint are mapped on the KucoinClient, and websocket subscriptions on the KucoinSocketClient. 
The SubscribeToTickerUpdates doesn't seem to give you volume info, however the SubscribeToSnapshotUpdates does contain the volume data, so I think you're looking for that.

**Comment by ertan2002** [comment]
thank you for the reply. As you said, I am using the SubscribeToTickerUpdates  method and can get the volume.
