### ISSUE TITLE
error on deserialize  kucoin stream order update

### ISSUE THREAD

**Issue by phase06** [JKorf/Kucoin.Net#44]
**Describe the bug**
Having error when deserialize socket KucoinStreamOrderBaseUpdate data

**To Reproduce**
1. Subscribed to  SubscribeToOrderUpdates
2. Place Order

**Expected behavior**
success deserialize data from server.

**Debug logging**
2021/06/12 16:31:59:256 | Kucoin     | Error | Deserialize JsonSerializationException: Error setting value to 'UpdateType' on 'Kucoin.Net.Objects.Sockets.KucoinStreamOrderBaseUpdate'.
2021/06/12 16:31:59:257 | Kucoin     | Warning | Failed to deserialize update: : Deserialize JsonSerializationException: Error setting value to 'UpdateType' on 'Kucoin.Net.Objects.Sockets.KucoinStreamOrderBaseUpdate'. {
  "data": {
    "symbol": "ETH-USDT",
    "orderType": "market",
    "side": "buy",
    "orderId": "**********",
    "type": "canceled",
    "orderTime": 1623486710303935777,
    "size": "10",
    "filledSize": "0.00000002",
    "remainFunds": "0",
    "funds": "0.00005189805",
    "clientOid": "******",
    "remainSize": "0",
    "status": "done",
    "ts": 1623486710303935777
  },
  "subject": "orderChange",
  "topic": "/spotMarket/tradeOrders",
  "channelType": "private",
  "type": "message",
  "userId": "**********"
}, data: {
  "data": {
    "symbol": "ETH-USDT",
    "orderType": "market",
    "side": "buy",
    "orderId": "**********",
    "type": "canceled",
    "orderTime": 1623486710303935777,
    "size": "10",
    "filledSize": "0.00000002",
    "remainFunds": "0",
    "funds": "0.00005189805",
    "clientOid": "**********",
    "remainSize": "0",
    "status": "done",
    "ts": 1623486710303935777
  },
  "subject": "orderChange",
  "topic": "/spotMarket/tradeOrders",
  "channelType": "private",
  "type": "message",
  "userId": "**********"
}

**Comment by JKorf** [comment]
Hi, this should be fixed in the latest beta release

**Comment by phase06** [comment]
Thanks @JKorf . May I know when is this planned to release in NuGet?
Or where do I get the bete release?

**Comment by phase06** [comment]
Got it, `Install-Package Kucoin.Net -Version 2.4.0-beta6`
