### ISSUE TITLE
Error starting order book synchronization: 404: not exist

### ISSUE THREAD

**Issue by ROMAN5** [JKorf/Kucoin.Net#45]
var orderBook = new KucoinSymbolOrderBook("BTC-USDT");
orderBook.OnStatusChange += (oldStatus, newStatus) => Console.WriteLine($"Book state changed from {oldStatus} to {newStatus}");
orderBook.OnOrderBookUpdate += (changedBids, changedAsks) => Console.WriteLine("Book updated");
var startResult = await orderBook.StartAsync();
if(!startResult.Success)
{
	Console.WriteLine("Error starting order book synchronization: " + startResult.Error);
	return;
}

Result:
Book state changed from Disconnected to Connecting
Book state changed from Connecting to Syncing
Error starting order book synchronization: **404: not exist**

**Comment by JKorf** [comment]
Hi, this has been fixed in the latest beta release

**Comment by sheldon1310** [comment]
> Hi, this has been fixed in the latest beta release

Where can I download the beta release?

**Comment by JKorf** [comment]
https://www.nuget.org/packages/Kucoin.Net/2.4.0-beta6

If you're using the package manager in Visual Studio you'll need to check the `Include perrelease` checkbox at the box.
