### ISSUE TITLE
Marging trade

### ISSUE THREAD

**Issue by AllTerrainDeveloper** [JKorf/Kucoin.Net#47]
**Describe the bug**
Margin operations are not implemented

I can't see or find anything referencing margin/burrow. Is there any plan to add margin features to this API, your Binance API already has it, which is quite useful, thank you for it.

For reference:
https://docs.kucoin.com/#post-borrow-order

**Comment by JoshuaRamirez** [comment]
+1

**Comment by hammadsajid786** [comment]
+1

**Comment by JKorf** [comment]
Available in latest option
