### ISSUE TITLE
KucoinStreamMatchBase does not include time field of underlying trade match data

### ISSUE THREAD

**Issue by jwdawson** [JKorf/Kucoin.Net#49]
The Client.Futures.SubscribeToTradeUpdatesAsync call results in a Kucoin call of Topic: /contractMarket/execution:{symbol} on the web socket. The resultant data should include a Time field of when the match executed but the KucoinStreamMatch data structure does not include a time field.

**Comment by jwdawson** [comment]
I have a branch that fixes this but dont have push access to this repo.

**Comment by jwdawson** [comment]
thanks. PR created. Also fixed an issue with order placement where optionals where not being optional. Feedback welcome. We are starting to use this library in our code so there may be more PRs coming in the future. :)

**Comment by JKorf** [comment]
Looks good. PR's are of course welcome, let me know if you have any issues :)
