### ISSUE TITLE
Client Order Id missing from futures trade update subscription message

### ISSUE THREAD

**Issue by jwdawson** [JKorf/Kucoin.Net#55]
**Describe the bug**
Client Order Id missing from futures trade update subscription message

**To Reproduce**
SocketClient.Futures.SubscribeToOrderUpdatesAsync

**Expected behavior**
Subscription data should have the Client Order Id.

**Debug logging**

**Comment by JKorf** [comment]
Thanks for the report. I've fixed this in the latest version
