### ISSUE TITLE
Why KucoinClient does not implement IExchangeClient ?

### ISSUE THREAD

**Issue by PsykotropyK** [JKorf/Kucoin.Net#58]
**Describe the bug**
Mostly a question more than a bug : why is `KucoinClient` not an `IExchangeClient` ?
All other clients I am using (Binance, Bitfinex, Kraken, FTX) are. 

**To Reproduce**
`IExchangeClient client = new KucoinClient()`

**Expected behavior**
All clients should expose the IExchangeClient interface

**Comment by JKorf** [comment]
Hi, it does, just on a slightly different level. You can use KucoinClient.Spot as IExchangeClient

**Comment by PsykotropyK** [comment]
Sorry for the question then : i actualy looked for IExchangeClient in the repo, and while today I see KucoinClientSpot my eyes got blurry yesterday....

Thank you for the very quick answer !!!
