### ISSUE TITLE
Add Margin and Pool in KucoinAccountType please

### ISSUE THREAD

**Issue by chichoncoin** [JKorf/Kucoin.Net#59]
**Describe the bug**
Deserialize JsonSerializationException: Error setting value to 'Type' on 'Kucoin.Net.Objects.Spot.KucoinAccount'.

**To Reproduce**
GetAccount with margin account

**Expected behavior**
Add Margin and Pool in KucoinAccountType please

**Comment by JKorf** [comment]
Fixed with latest version
