### ISSUE TITLE
Critical Bug. AverageEntryPrice is 0 in FuturesPosition

### ISSUE THREAD

**Issue by Megwebbiz** [JKorf/Kucoin.Net#65]
Hi
I have a critical error in client.Futures.GetPositionsAsync(). in result AverageEntryPrice  is 0 and i can not find any field to distinguish Entry Price of a position.

Thanks

**Comment by JKorf** [comment]
This should be fixed in latest version

**Comment by Megwebbiz** [comment]
Hi man
in latest version this issue has been solved.
Thank you JKorf

**Comment by Megwebbiz** [comment]
Hi man
in latest version this issue has been solved.
Thank you JKorf
