### ISSUE TITLE
Wrong property name in KucoinAccountActivity

### ISSUE THREAD

**Issue by kyumit** [JKorf/Kucoin.Net#66]
https://github.com/JKorf/Kucoin.Net/blob/4da92badccce9031184f51daf7274d986d7faba2/Kucoin.Net/Objects/Spot/KucoinAccountActivity.cs#L21

`Quantity` have to be `Amount` as defined in the docs: https://docs.kucoin.com/#get-account-ledgers

Edit: `AccountType` is missing as well.

**Comment by JKorf** [comment]
Quantity parsing has been fixed, account type will be fixed in next version
