### ISSUE TITLE
Random websocket connection closed issue

### ISSUE THREAD

**Issue by Amitabitbul** [JKorf/Kucoin.Net#67]
**Describe the bug**
Random WebSocket connection closed and reconnect handshake fails for an unknown reason

**To Reproduce**
await _socketClient.Spot.SubscribeToBalanceChangesAsync()
await _socketClient.Spot.SubscribeToOrderUpdatesAsync()

**Expected behavior**
When the socket closed or failed, reconnect.
**Debug logging**
Kucoin[Spot] | Socket 1 error: Websocket error code ConnectionClosedPrematurely, details: WebSocketException - The remote party closed the WebSocket connection without completing the close handshake.
IOException - Unable to read data from the transport connection: Connection reset by peer.
SocketException - Connection reset by peer at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
Kucoin[Spot] | Socket 2 error: Websocket error code ConnectionClosedPrematurely, details: WebSocketException - The remote party closed the WebSocket connection without completing the close handshake.

Kucoin[Spot] \| Socket 1 error: Websocket error code ConnectionClosedPrematurely, details: WebSocketException - The remote party closed the WebSocket connection without completing the close handshake.
--
  | 2021-10-17T09:02:00.072+03:00 | at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
  | 2021-10-17T09:02:00.072+03:00 | at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
  | 2021-10-17T09:02:00.072+03:00 | at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
  | 2021-10-17T09:02:00.072+03:00 | at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ReceiveLoopAsync()

Kucoin[Spot] \| Socket 1 error: Websocket error code ConnectionClosedPrematurely, details: WebSocketException - The remote party closed the WebSocket connection without completing the close handshake.
--
  | 2021-10-17T09:01:05.454+03:00 | at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
  | 2021-10-17T09:01:05.454+03:00 | at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
  | 2021-10-17T09:01:05.454+03:00 | at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
  | 2021-10-17T09:01:05.454+03:00 | at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ReceiveLoopAsync()

Thanks!

**Comment by JKorf** [comment]
It should reconnect after those messages

**Comment by Amitabitbul** [comment]
> It should reconnect after those messages

But it doesn't 😅

**Comment by JKorf** [comment]
Are you using the latest version? What versions of Kucoin.Net and CryptoExchange.Net? Is there no further logging after those messages?

**Comment by Amitabitbul** [comment]
> Are you using the latest version? What versions of Kucoin.Net and CryptoExchange.Net? Is there no further logging after those messages?

`<PackageReference Include="Kucoin.Net" Version="3.1.4" />`
There is no reference to CryptoExchange.Net

btw, It's good to have you back ;)

**Comment by jrance** [comment]
I'm getting the same error after the process has been running for a while. It usually happens about 12 to 24 hours after the subscriptions were initialized. I see the following message after the exception but it never seems to reconnect.

2021/11/03 14:21:26:345 | Information | Kucoin[Spot] | Socket 1 Connection lost, will try to reconnect after 00:00:05

I've hooked up to your latest code and set a breakpoint at that log entry. I'll post some more information when it happens again.

**Comment by JKorf** [comment]
Thanks, let me know if you find anything.

**Comment by Amitabitbul** [comment]
> I'm getting the same error after the process has been running for a while. It usually happens about 12 to 24 hours after the subscriptions were initialized. I see the following message after the exception but it never seems to reconnect.
> 
> 2021/11/03 14:21:26:345 | Information | Kucoin[Spot] | Socket 1 Connection lost, will try to reconnect after 00:00:05
> 
> I've hooked up to your latest code and set a breakpoint at that log entry. I'll post some more information when it happens again.

Is it still happening in latest version?

**Comment by JKorf** [comment]
There have been some improvements in the latest versions. As this has gone a bit stale I'll close this for now. If you're still having issues with the latest version please let me know
