### ISSUE TITLE
Margin socket subscriptions missing in the latest release

### ISSUE THREAD

**Issue by solidfoundationsoftware** [JKorf/Kucoin.Net#68]
After updating my project from 2.3.9 to 3.1.4 I noticed that some margin subscriptions are missing. Order book updated related to lending/borrowing are no longer available. They are referring to them in their documentation as: 
Topic: /margin/fundingBook:{currency0},{currency1}...

Subscribe to this topic to get the order book changes on margin trade.

Thank you for your hard work in providing this library!

**Comment by JKorf** [comment]
Hi, these were missing from the interface, I've re-added them so it should be available again in the latest version
