### ISSUE TITLE
(Possible Regretion) Why KukoinClient not implement IExchangeClient now?

### ISSUE THREAD

**Issue by heavymanto** [JKorf/Kucoin.Net#69]
**Describe the bug**
I would like use KukoinClient  by IExchangeClient interface. In doc it said "This library is build upon the CryptoExchange.Net library". 

seems to have disappeared with the last commit

https://github.com/JKorf/Kucoin.Net/commit/2d4da05c800d887b71b079530293b8ee45992844#diff-f0ba760908ed6e2c85537c3fc6baee42cff45a24be91b0dd64d298f03431895d

![image](https://user-images.githubusercontent.com/6449169/137623803-4f616973-347d-4933-8b2b-13df5f3acd3c.png)

**Comment by JKorf** [comment]
It was changed to the specific Spot and Futures implementation.
So the IExchangeClient interface is on KucoinClient.Spot now
