### ISSUE TITLE
OCO Trading

### ISSUE THREAD

**Issue by thraxxus** [JKorf/Kucoin.Net#7]
Has anyone gotten an OCO order to work?
I am trading RENUSDT with PlaceOCOOrder call and all I get is that OCO is not allowed for that pair - thing is, according to the exchange it is.

Error: ERROR Trading: -1013: Stop loss orders are not supported for this symbol. 

Thoughts?

**Comment by JKorf** [comment]
Hi, the Kucoin client doesn't have a `PlaceOCOOrder` method. Did you mean Binance?
