### ISSUE TITLE
Sign error for authenticated endpoint when uri parameters contains escaped chars

### ISSUE THREAD

**Issue by andreafi** [JKorf/Kucoin.Net#72]
This is an example of signData variable value in KucoinAuthenticationProvider

"1634762102597GET/api/v1/withdrawals/quotas?currency=CTSI&chain=BEP20%28BSC%29"

Due to excaped chars (done in "CreateParamString" extension in CryptoExchange.Net.ExtensionMethods class) the request is rejected by kucoin with:

400005: Invalid KC-API-SIGN

The corrent signData value should be:

"1634762102597GET/api/v1/withdrawals/quotas?currency=CTSI&chain=BEP20(BSC)"

One solution could be to add  the Uri.UnescapeDataString function in KucoinAuthenticationProvider class, changing the AddAuthenticationToHeaders function from: 

            ........................
            var signData = result["KC-API-TIMESTAMP"] + method + uri + jsonContent;
            ........................

to

            ........................
            var signData = result["KC-API-TIMESTAMP"] + method + Uri.UnescapeDataString(uri) + jsonContent;
            ........................
 
A more clean solution would be to pass  the original uri without escaping, to the AddAuthenticationToHeaders function.

Thanks.

Andrea

**Comment by JKorf** [comment]
For now I've quick fixed it with the solution you proposed, in the future I might refactor it in favor of a solution in the CryptoExchange lib

**Comment by JKorf** [comment]
With the latest versions the Uri is passed to the Authentication provider and uri.PathAndQuery is used, so I'm closing this
