### ISSUE TITLE
How to get balances

### ISSUE THREAD

**Issue by Trumpeta2021** [JKorf/Kucoin.Net#73]
Hello,
hot to get ballances from trading account, please? I can't find it :(

**Comment by Megwebbiz** [comment]
hi
for futures and USDT balance:
client = new KucoinClient();
client.Futures.SetApiCredentials(API_Key, API_Secret, API_Pass);
var AvailableUSDT = await client.Futures.GetAccountOverviewAsync("USDT");
lblStatus.Text = "Available USDT: " + AvailableUSDT.Data.AvailableBalance.ToString();
