### ISSUE TITLE
Futures GetOrdersAsync serialization issue.

### ISSUE THREAD

**Issue by bbrookshire** [JKorf/Kucoin.Net#75]
Trying to get futures orders.

var client = new KucoinClient(new KucoinClientOptions()
{	
	FuturesApiCredentials = new KucoinApiCredentials("MY", "INFO", "REMOVED")
});

var ordersCallResult = client.Futures.GetOrdersAsync();
if (ordersCallResult.Result.Success)
{
	var orders = ordersCallResult.Result.Data;
}

The result is not successful, and the following is the error:

{: Deserialize JsonSerializationException: Error setting value to 'StopPriceType' on 'Kucoin.Net.Objects.Futures.KucoinFuturesOrder'. [Data only available in Debug LogLevel]}

**Comment by JKorf** [comment]
This should be fixed in the latest version

**Comment by bbrookshire** [comment]
Strange.  I got latest, but it's still failing for me.

**Comment by bbrookshire** [comment]
Update;  Same issue with TimeInForce.  Also needed to be nullable.  Working now with that change.

**Comment by JKorf** [comment]
Thanks for the update, this should be fixed in version 3.1.6
