### ISSUE TITLE
get previous day price

### ISSUE THREAD

**Issue by keyvan1361** [JKorf/Kucoin.Net#76]
Hi,
How can I get the price of my asset for the previous day?
sth like this is available in binance:
 `client.Spot.Market.Get24HPrice(crypto).Data.PrevDayClosePrice`
my code is:
`var balance = await client.Spot.GetAccountsAsync()`
I even used this but does not have what I need:
`client.Spot.Get24HourStatsAsync(item.Currency + "-USDT")`

**Comment by JKorf** [comment]
You could just use this no?
````C#
var stats = await client.Spot.Get24HourStatsAsync(item.Currency + "-USDT");
var price24hAgo = stats .Data.LastPrice - stats.Data.ChangePrice;
````
