### ISSUE TITLE
client.Futures.GetUntriggeredStopOrdersAsync() Error

### ISSUE THREAD

**Issue by Megwebbiz** [JKorf/Kucoin.Net#77]
Hi man
i have a error in :
client.Futures.GetUntriggeredStopOrdersAsync()

Error:
Deserialize JsonSerializationException: Error converting value {null} to type 'System.Boolean'. Path 'data.items[0].stopTriggered', line 1, position 298.

thank you again

**Comment by JKorf** [comment]
Hi, this should be fixed in version 3.1.6

**Comment by Megwebbiz** [comment]
Hi man
This error has been solved.
Thank you alot
