### ISSUE TITLE
client.Futures.GetCompletedOrdersAsync() Error

### ISSUE THREAD

**Issue by Megwebbiz** [JKorf/Kucoin.Net#78]
Hi man
I have an error in :
**client.Futures.GetCompletedOrdersAsync();**
Error:
**Deserialize JsonSerializationException: Error setting value to 'TimeInForce' on 'Kucoin.Net.Objects.Futures.KucoinFuturesOrder'.**

Thank you again

**Comment by JKorf** [comment]
Should be fixed in version 3.1.6

**Comment by Megwebbiz** [comment]
Hi man
This error has been solved.
Thank you a lot.
