### ISSUE TITLE
SubscribeToOwnMatchEngineUpdatesAsync() does not work

### ISSUE THREAD

**Issue by axelarati** [JKorf/Kucoin.Net#8]
I get the error "KC-API-KEY not exists" when I try to subscribe to my own matches, but this can't be possible since I was able to subscribe to the ticker stream (SubscribeToTickerUpdatesAsync).

I am using the kucoin sandbox (with endpoint https://openapi-sandbox.kucoin.com/api/), so this could be the source of the issue.

Edit: I realized that the ticker stream probably doesn't require authentication, but the api credentials I used work for the rest client, so they should also work for the socket client.

**Comment by JKorf** [comment]
Hi, I think the issue is the socket client making use of the rest client for authenticated endpoints. Can you try to set the default options on the rest client (`SetDefaultOptions`) to the same API endpoint and see if that works?
