### ISSUE TITLE
No way to use Kucoin Sanbox

### ISSUE THREAD

**Issue by Darkatek7** [JKorf/Kucoin.Net#82]
Hey there, 

I wanted to try out the wrapper and was trying it out with the Kucoin Sandbox as well as the normal kucoin site. Sadly I couldn't get it to work on the sandbox site.

I tried setting the KucoinClient options BaseAdress both to 
Website: https://sandbox.kucoin.com
REST API: https://openapi-sandbox.kucoin.com
which didn't help me get it to work.

Thanks for your reply.

**Comment by JKorf** [comment]
Try `https://openapi-sandbox.kucoin.com/api/`

**Comment by Darkatek7** [comment]
Doesn't seem to work either

**Comment by Darkatek7** [comment]
This works, thank you :)
