### ISSUE TITLE
AcoountId how can I learn?

### ISSUE THREAD

**Issue by allcasper99** [JKorf/Kucoin.Net#88]
When I use Spot.GetAccountAsync function it asks me for account id. Where can I learn this?

User Profile / UID：887XXXXX I am getting an error when I use it. Am I doing the right thing?

can you help me?

**Comment by JKorf** [comment]
Use `GetAccountsAsync()` first, it'll return you this

**Comment by allcasper99** [comment]
thank you. I will try and let you know the results

**Comment by allcasper99** [comment]
The client.Spot.GetAccountAsync() method gives an error when the accountid information is not entered. When I enter the UID: 888xxx information under my user profile, it says account not found. Please can you help me. I am sharing the screenshots below.

![account](https://user-images.githubusercontent.com/77941443/142930871-37b522ae-6607-4b5e-9696-78507c40831f.png)

![program](https://user-images.githubusercontent.com/77941443/142930968-5680423f-c586-42b2-b7f4-c6961fc4db20.png)

**Comment by JKorf** [comment]
As I said, you need to query the `GetAccountsAsync` endpoint. (note the plural)
