### ISSUE TITLE
Debug Message not handled when subscribed to SubscribeToOwnMatchEngineUpdates

### ISSUE THREAD

**Issue by kNOCKEYY** [JKorf/Kucoin.Net#9]
When I subscribe to order updates via SubscribeToOwnMatchEngineUpdates and a Order is made I get a Debug log with message not handled and the data of the update.

Debug:
2020.05.01 18:32:37:080 | Error | Socket 1 Exception during message processing
Exception: System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at Kucoin.Net.KucoinSocketClient.<>cDisplayClass27_0.<SubscribeToOwnMatchEngineUpdatesAsync>b0(JToken tokenData)
   at CryptoExchange.Net.SocketClient.<>cDisplayClass52_0`1.<AddHandler>gInternalHandler|0(SocketConnection socketWrapper, JToken data)
   at CryptoExchange.Net.Sockets.SocketConnection.HandleData(JToken tokenData)
Data: {
  "data": {
    "sequence": "1583978471435",
    "symbol": "BTC-USDT",
    "reason": "filled",
    "side": "buy",
    "orderId": "5eac4f24d7f2ea00094b3f18",
    "time": "1588350756514635626",
    "type": "done"
  },
  "subject": "trade.l3done",
  "topic": "/market/level3:BTC-USDT",
  "channelType": "private",
  "type": "message",
  "userId": "5e89d92434c5550008773f7b"
}

2020.05.01 18:32:37:082 | Debug | Message not handled: {
  "data": {
    "sequence": "1583978471435",
    "symbol": "BTC-USDT",
    "reason": "filled",
    "side": "buy",
    "orderId": "5eac4f24d7f2ea00094b3f18",
    "time": "1588350756514635626",
    "type": "done"
  },
  "subject": "trade.l3done",
  "topic": "/market/level3:BTC-USDT",
  "channelType": "private",
  "type": "message",
  "userId": "5e89d92434c5550008773f7b"
}
2020.05.01 18:32:41:029 | Debug | Sending periodic
2020.05.01 18:32:41:035 | Debug | Socket 1 sending data: {"id":"1588350761032","type":"ping"}
2020.05.01 18:32:41:337 | Debug | Socket 1 received data: {"id":"1588350761032","type":"pong"}

**Comment by kNOCKEYY** [comment]
Oh, I also found a similar problem in the Bitfinex.net library. 
https://github.com/JKorf/Bitfinex.Net/issues/114

**Comment by JKorf** [comment]
This was a parsing issue, should be fixed in the latest version.
