### ISSUE TITLE
Exception on istance KucoinClient (package 2.3.9)

### ISSUE THREAD

**Issue by heavymanto** [JKorf/Kucoin.Net#90]
**Describe the bug**
Method 'add_OnOrderPlaced' in type 'Kucoin.Net.KucoinClient' from assembly 'Kucoin.Net, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**To Reproduce**
  _client = new KucoinClient(new KucoinClientOptions
            {
                ApiCredentials = new KucoinApiCredentials(_exchange.Key_Private, _exchange.Key_Secret, _exchange.Key_Pass)
            });

**Comment by JKorf** [comment]
These type of errors are thrown by version miss matches. Your CryptoExchange.Net version and Kucoin.Net version probably don't match, or you have other libraries in your project which rely on a different version of CryptoExchange.Net
