### ISSUE TITLE
No credentials provided for private endpoint

### ISSUE THREAD

**Issue by Ramin-cs** [JKorf/Kucoin.Net#91]
I used this code and im sure my key &secret &and passphrase is true
but i got this error
No credentials provided for private endpoint

Code :
            var client = new KucoinClient(new KucoinClientOptions()
            {
                ApiCredentials = new KucoinApiCredentials("mykey", "mysecret", "mypass")

            });
            
            var c = await client.Futures.PlaceOrderAsync("XRPUSDT", Kucoin.Net.Objects.KucoinOrderSide.Buy, Kucoin.Net.Objects.KucoinNewOrderType.Market, 50, 50);

            Console.WriteLine(c.Success);
            Console.WriteLine(c.Error);
            Console.ReadKey();

**Comment by Ramin-cs** [comment]
tnx for your replay
now i got this error :D
400003: KC-API-KEY not exists
im sure my infromation is right

this is my code : 
            var client = new KucoinClient(new KucoinClientOptions()
            {

                FuturesApiCredentials=new KucoinApiCredentials("mykey", "mysecret", "mypass")
            });
            var cc = await client.Futures.PlaceOrderAsync("BTCUSDT", KucoinOrderSide.Buy, KucoinNewOrderType.Market, 10, 50, null, KucoinTimeInForce.FillOrKill);
            Console.WriteLine(cc.Error);
            Console.ReadKey();

**Comment by JKorf** [comment]
Is it an API key for the futures API? I'm pretty sure you need a different API key for futures trading as for spot trading
