### ISSUE TITLE
PlaceMarginOrderAsync return Success ok but data is null

### ISSUE THREAD

**Issue by heavymanto** [JKorf/Kucoin.Net#92]
**Describe the bug**

I try to place market order. The response is 200 and success true,, but Data property is null

 string symbolPair = GetSymbolPairName(symbol);
            KucoinOrderSide _operation = (KucoinOrderSide)(int)operation;

            var order = _client.Spot.PlaceMarginOrderAsync(symbolPair, _operation, KucoinNewOrderType.Market, null, amount);
            order.Wait();
            if (order.Result.Success)
            {
                return order.Result.Data.OrderId.ToString();
            }

**Debug logging**
![KuCoin_PlaceOrder](https://user-images.githubusercontent.com/6449169/144707743-7dec43fb-6f27-482c-9fb7-7bea75ac92bc.PNG)

**Comment by JKorf** [comment]
That doesn't seem right. Can you have a look at what data is returned by either setting `OutputOriginalData` to true in the client options, which will fill the `OriginalData` property in the result, or setting `LogLevel` to `Trace` which will log the send/received data?

**Comment by JKorf** [comment]
I've checked this, and if your margin account isn't open the server responds with success status (code 200000), but with no data and a chinese error message: 杠杆交易未开通. It roughly translates to something with `margin not open`. So the call isn't successful, but the server return success status, which is an issue on their side really.. 

With an open margin account it seems to work as expected.

**Comment by heavymanto** [comment]
thank I check my account.
