### ISSUE TITLE
SubscribeToOrderUpdatesAsync -> onOrderData -- returns order status as Cancelled for Market orders Even it succeeded.

### ISSUE THREAD

**Issue by kayahasa** [JKorf/Kucoin.Net#96]
Hi,

I want to listen a custom account orders by subscribing SubscribeToOrderUpdatesAsync.

When i put market order, 
An order comes to the onOrderData with the status of Cancelled event the order is successfull.

This is really big issue for the systems. 

Could you please correct it?

**Comment by JKorf** [comment]
Hi, can you provide some logging of what the response is?

**Comment by kayahasa** [comment]
There is no response, 

I am listenin socket data on SubscribeToOrderUpdatesAsync. After putting market order on exchange, and if you listen to the SubscribeToOrderUpdatesAsync->onOrderData stream, you will see that there will be notification with the order details but the order status is cancelled.(It is filled on exchange)

**Comment by JKorf** [comment]
I've  tried this, and you're right, it does have cancel state. It is however an issue from the server, not the library. Looking at the received data I get this for a market order:
````
2021/12/14 20:36:14:092 | Trace | Kucoin[Spot] | Socket 1 received data: {"type":"message","topic":"/spotMarket/tradeOrders","userId":"","channelType":"private","subject":"orderChange","data":{"symbol":"BTC-USDT","orderType":"market","side":"buy","orderId":"61b8f22d4592c200011dc0d9","liquidity":"taker","type":"match","orderTime":1639510573780309787,"filledSize":"0.00021303","remainFunds":"0.000052255","funds":"10","matchPrice":"46941.5","matchSize":"0.00021303","tradeId":"61b8f22d2e113d292383175b","remainSize":"0","status":"match","ts":1639510573780309787}}

2021/12/14 20:36:14:191 | Trace | Kucoin[Spot] | Socket 1 received data: {"type":"message","topic":"/spotMarket/tradeOrders","userId":"","channelType":"private","subject":"orderChange","data":{"symbol":"BTC-USDT","orderType":"market","side":"buy","orderId":"61b8f22d4592c200011dc0d9","type":"canceled","orderTime":1639510573780309787,"filledSize":"0.00021303","remainFunds":"0","funds":"10","remainSize":"0","status":"done","ts":1639510573780309787}}
````

As you can see the first update is of type `match`, which is expected, but the second update is of type `canceled` for some reason.

This is not something I can fix in this library, you might want to contact Kucoin about it.

**Comment by kayahasa** [comment]
My comment is, 
since it is Market Order, Actually the status is not important. Because a market order cannot be cancelled and it MUST BE Filled. That is why, i omitted order status if the order type is Market Order. 

So, i think this will not be a problem.

What is your opinion?

**Comment by JKorf** [comment]
That makes sense yes. Still its odd from the server. But you are right, on a market order the status isn't important as it will always be filled immediately

**Comment by kayahasa** [comment]
Thanks for support and colloboration.
