### ISSUE TITLE
Futures Order Insufficient Balance

### ISSUE THREAD

**Issue by mdobson8** [JKorf/Kucoin.Net#97]
I am trying to place futures orders but every time it seems to be calculating at way more than it should.

Example below;
Buy - TRXUSDTM - Limit - 2x lev - size 125 - price 0.08 
buy order: 
buy order: 300003: Balance insufficient. The order would cost 501.5000000000. 

In reality the order should be costing way less than 501. Am I missing something or are the calculations completely wrong?

**Comment by JKorf** [comment]
Hi, sorry for the late response.
The API works with 'lots' which is not the same as a single unit of the asset. For example, the current lot size of TRXUSDTM is 100trx. So when you set a buy order of quantity 10, it would actually be for 1000trx. 
Hope that clears things up

**Comment by hamedmaleki1366** [comment]
Hello @JKorf. 
How can I take 'lots' value? I see it's equal to 1. 

`symbols.FirstOrDefault(x => x.Name == "TRXUSDTM")?.SourceObject as
                Kucoin.Net.Objects.Models.Futures.KucoinContract;
var lotSize =
                symbolExtra?.LotSize;
`

The value of "lotSize" is 1. Where is 100 for lots? 

Thanks in advance.

**Comment by JKorf** [comment]
You'll have to use the Multiplier property
