### ISSUE TITLE
Getting no order updates on Socket when placing an order

### ISSUE THREAD

**Issue by pahager** [JKorf/Kucoin.Net#98]
After placing an order like this:
` await this.KucoinClient.Spot.PlaceOrderAsync($"{Symbol}", null, KucoinOrderSide.Buy, KucoinNewOrderType.Limit, quantity: _outputQuantity, price: PriceToBuy, timeInForce: KucoinTimeInForce.GoodTillCancelled);` I am getting no update on the socket subscription, but order is showed on the website. If I am placing an order on the website, then I am getting immediately an Update to the socket. What am I doing wrong when placing an order?

**Comment by JKorf** [comment]
There should be no difference in whether you place the order via the API or via the website. I suggest turning on trace logging in the client options and see what data is send/received. If an order is successfully placed you'll always get an update in the socket subscription handler. (unless there is some issue on the server)

**Comment by pahager** [comment]
My mistake, I was not subscribed to order updates before placing an order... Thanks anyway for your response.
